const ticker2industry = {
  FATN11: 'Mercados de Capitais',
  KISU11: '',
  MMMC34: 'Conglomerados Industriais',
  RRRP3: 'Petróleo e Gás - Integrados',
  FISC11: 'Fundos de Investimento Imobiliário (FIIs)',
  BIVB39: '',
  P1SX34: 'Óleo, Gás e Combustíveis Consumíveis',
  ESUT11: 'Mercados de Capitais',
  A1OS34: 'Produtos de construção',
  GOGL34: 'Mídia e Serviços Interativos',
  CEAB3: 'Varejo Especializado',
  EPAR3: 'Fabricantes de Automóveis e Caminhões',
  GPIV33: 'Mercados de Capitais',
  BRGE5: 'Serviços Financeiros Diversificados',
  ELET5: 'Eléctricas',
  ESUD11: 'Mercados de Capitais',
  CEBR5: 'Infraestrutura Elétrica',
  CSRN5: 'Infraestrutura Elétrica',
  A1BB34: 'Equipamentos Elétricos',
  ABTT34: 'Equipamentos e Suprimentos Médicos',
  ABBV34: 'Biotecnologia',
  ABCB4: 'Bancos',
  A1BM34: 'Equipamentos e Suprimentos Médicos',
  ACNB34: 'Serviços de TI',
  EALT4: 'Metais e Mineração',
  EALT3: 'Metais e Mineração',
  ATVI34: 'Entretenimento',
  BACW39: 'Mercados de Capitais',
  CALI4: 'Construção e Engenharia',
  BRGE3: 'Serviços Financeiros Diversificados',
  BRGE8: 'Serviços Financeiros Diversificados',
  BRGE6: 'Serviços Financeiros Diversificados',
  BRGE11: 'Serviços Financeiros Diversificados',
  BRGE12: 'Serviços Financeiros Diversificados',
  ADBE34: 'Software',
  ADPR34: 'Serviços de TI',
  A1AP34: 'Varejo Especializado',
  A1MD34: 'Semicondutores e Equipamentos Associados',
  AERI3: 'Equipamentos Elétricos',
  TIET3: 'Eléctricas',
  TIET4: 'Eléctricas',
  AESB3: 'Eléctricas',
  A1ES34: 'Produtores de Eletricidade independentes e Energia Renovável',
  AFHI11: '',
  AFCR11: 'Mercados de Capitais',
  A1FL34: 'Seguro',
  AFLT3: 'Infraestrutura Elétrica',
  DBAG34: '',
  C1SU34: 'Mercados de Capitais',
  A1GI34: 'Ferramentas e Serviços de Ciências da Vida',
  SLCE3: 'Produtos alimentícios',
  QAGR11: 'Mercados de Capitais',
  BTAL11: '',
  AGXY3: '',
  AIGB34: '',
  A1LK34: 'Companhias Aéreas',
  S1EA34: 'Contêineres e Embalagens',
  A1PD34: 'Químicos',
  DEAI34: 'Companhias Aéreas',
  W1AB34: 'Maquinário',
  AIRB34: 'Hotéis, Restaurantes e Lazer',
  AALL34: 'Companhias Aéreas',
  U1AL34: 'Companhias Aéreas',
  S1OU34: 'Companhias Aéreas',
  A1KA34: 'Serviços de TI',
  RZAK11: 'Mercados de Capitais',
  A1LB34: 'Químicos',
  A1RE34: 'Fundos de Investimento Imobiliário (FIIs)',
  A1LX34: 'Biotecnologia',
  RPAD5: 'Bancos',
  RPAD3: 'Bancos',
  BRIV4: 'Bancos',
  CRIV4: 'Finanças de consumo',
  BRIV3: 'Bancos',
  CRIV3: 'Finanças de consumo',
  RPAD6: 'Bancos',
  CSAB4: 'Seguro',
  PEAB3: 'Conglomerados Industriais',
  PEAB4: 'Conglomerados Industriais',
  CSAB3: 'Seguro',
  ALSO3: 'Gestão e Desenvolvimento Imobiliário',
  ALZR11: 'Mercados de Capitais',
  BABA34: 'Internet e Varejo de Marketing Digital',
  A1LG34: 'Equipamentos e Suprimentos Médicos',
  BAUH4: 'Produtos alimentícios',
  A1GN34: 'Produtos de construção',
  A1LL34: 'Serviços de TI',
  A1EN34: 'Infraestrutura Elétrica',
  AALR3: 'Serviços e Fornecedores de Saúde',
  ALLD3: 'Varejo Especializado',
  JPPA11: 'Mercados de Capitais',
  ALPK3: 'Serviços Comerciais & Suprimentos',
  A1TT34: 'Seguro',
  ALMI11: '',
  ALPA3: 'Têxteis, Vestuário e Produtos de Luxo',
  ALPA4: 'Têxteis, Vestuário e Produtos de Luxo',
  APER3: 'Seguro',
  RBRF11: 'Mercados de Capitais',
  GOGL35: 'Mídia e Serviços Interativos',
  AVLL3: 'Bens domésticos duráveis',
  RIOS3: '',
  MOOO34: 'Tabaco',
  ALUP3: 'Eléctricas',
  ALUP11: 'Eléctricas',
  ALUP4: 'Eléctricas',
  AMZO34: 'Internet e Varejo de Marketing Digital',
  BAZA3: 'Bancos',
  ABEV3: 'Bebidas',
  AMBP3: 'Atividades de Gestão de Resíduo',
  A1EE34: 'Infraestrutura Variada',
  M1AA34: 'Fundos de Investimento Imobiliário (FIIs)',
  SULA4: 'Seguro',
  A1MX34: '',
  BOAC34: '',
  SULA3: 'Seguro',
  SULA11: 'Seguro',
  NOKI34: 'Equipamentos de Comunicação',
  A1EP34: 'Infraestrutura Elétrica',
  T1OW34: 'Fundos de Investimento Imobiliário (FIIs)',
  B1TI34: 'Tabaco',
  AXPB34: '',
  A1WK34: 'Captação, Tratamento e Distribuição de Água',
  LAME4: 'Comercio Varejista (Departamento e Desconto)',
  LAME3: 'Comercio Varejista (Departamento e Desconto)',
  E1NI34: 'Infraestrutura Elétrica',
  A1MP34: 'Mercados de Capitais',
  A1MB34: 'Serviços e Fornecedores de Saúde',
  A1ME34: 'Equipamentos Elétricos',
  AMGN34: 'Biotecnologia',
  A1PH34: 'Equipamentos, Instrumentos e Componentes Eletrônicos',
  CBEE3: 'Infraestrutura Elétrica',
  A1DI34: 'Semicondutores e Equipamentos Associados',
  V1RS34: 'Serviços Profissionais',
  A1IV34: '',
  SPGI34: 'Mercados de Capitais',
  CARE11: 'Fundos de Investimento Imobiliário (FIIs)',
  B1DX34: 'Equipamentos e Suprimentos Médicos',
  ATSA11: 'Mercados de Capitais',
  FAED11: 'Fundos de Investimento Imobiliário (FIIs)',
  PQAG11: 'Mercados de Capitais',
  ABUD34: 'Bebidas',
  ANIM3: 'Educação',
  ANIM3T: '',
  A1NS34: 'Software',
  A1NT34: 'Serviços e Fornecedores de Saúde',
  A1ON34: 'Seguro',
  A1PA34: 'Óleo, Gás e Combustíveis Consumíveis',
  AAPL34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  A1MT34: 'Semicondutores e Equipamentos Associados',
  APTV34: 'Componentes Automotivos',
  MOAR3: 'Serviços Financeiros Diversificados',
  ARMT34: 'Metais e Mineração',
  A1DM34: 'Produtos alimentícios',
  ARNC34: 'Espaço Aéreo e Defesa',
  ARCT11: 'Mercados de Capitais',
  ARZZ3: 'Calçados',
  A1NE34: 'Equipamentos de Comunicação',
  TASA3: 'Espaço Aéreo e Defesa',
  TASA4: 'Espaço Aéreo e Defesa',
  TASA13: '',
  TASA17: '',
  TASA15: '',
  U1AI34: 'Têxteis, Vestuário e Produtos de Luxo',
  A1JG34: 'Seguro',
  EAIN34: 'Entretenimento',
  A1SN34: 'Biotecnologia',
  N1VO34: 'Produtos farmacêuticos',
  ASML34: 'Semicondutores e Equipamentos Associados',
  ASAI3: 'Processamento de Alimentos',
  J1KH34: 'Serviços de TI',
  A1SU34: 'Seguro',
  A1ZN34: 'Produtos farmacêuticos',
  BCIA11: 'Fundos de Investimento Imobiliário (FIIs)',
  FIGS11: 'Fundos de Investimento Imobiliário (FIIs)',
  TGAR11: 'Mercados de Capitais',
  HSAF11: 'Mercados de Capitais',
  VSPT3: 'Rodovia e Ferrovia',
  ATMP3: 'Serviços Comerciais & Suprimentos',
  A1TM34: 'Infraestrutura de Gás',
  ATOM3: 'Serviços Diversificados de Telecomunicação',
  ATTB34: 'Serviços Diversificados de Telecomunicação',
  AURA33: 'Metais e Mineração',
  A1UT34: 'Software',
  R1OK34: 'Equipamentos Elétricos',
  AIEC11: 'Mercados de Capitais',
  A1VB34: 'Fundos de Investimento Imobiliário (FIIs)',
  A1VY34: 'Contêineres e Embalagens',
  AZEV3: 'Construção e Engenharia',
  AZEV4: 'Construção e Engenharia',
  AZUL4: 'Transporte Aéreo',
  PCAR3: 'Comércio Varejista de Produtos Alimentícios',
  EQPA6: 'Infraestrutura Elétrica',
  J1BH34: 'Rodovia e Ferrovia',
  JBDU3: 'Papel e Produtos Florestais',
  BRKM6: 'Fabricação de Produtos Químicos',
  CPLE6: 'Infraestrutura Elétrica',
  CEBR6: 'Infraestrutura Elétrica',
  CSRN6: 'Infraestrutura Elétrica',
  JBDU4: 'Papel e Produtos Florestais',
  BTOW3: 'Internet e Varejo de Marketing Digital',
  B3SA3: 'Mercados de Capitais',
  BAHI3: 'Mercados de Capitais',
  BIDU34: 'Mídia e Serviços Interativos',
  B1KR34: 'Equipamentos e serviços de energia',
  B1LL34: 'Contêineres e Embalagens',
  BBAS3: 'Bancos de Centro Monetário',
  BMEB4: 'Bancos',
  BIDI4: 'Bancos Regionais',
  BPAC3: 'Mercados de Capitais',
  BIDI11: 'Bancos Regionais',
  BGIP3: 'Bancos',
  BMEB3: 'Bancos',
  BMIN3: 'Mercados de Capitais',
  MODL11: '',
  BMGB4: 'Bancos',
  BIDI3: 'Bancos Regionais',
  BIDI4T: '',
  BPAC5: 'Mercados de Capitais',
  BSLI3: 'Bancos',
  BPAN4: 'Bancos Regionais',
  BCSA34: 'Bancos',
  BMIN4: 'Mercados de Capitais',
  USBC34: 'Bancos',
  FFTD34: 'Bancos',
  Z1IO34: 'Bancos',
  H1BA34: 'Bancos',
  BGIP4: 'Bancos',
  BCRI11: 'Fundos de Investimento Hipotecários',
  BEES3: 'Bancos',
  BEES4: 'Bancos',
  BONY34: '',
  F1RC34: 'Bancos',
  M1TB34: 'Bancos',
  MSBR34: '',
  H1DB34: 'Bancos',
  I1BN34: 'Bancos',
  L1YG34: 'Bancos',
  BRSR5: 'Bancos',
  BRSR6: 'Bancos',
  BRSR3: 'Bancos',
  BNFS11: 'Mercados de Capitais',
  B1CS34: '',
  BDLL4: 'Maquinário',
  BARI11: 'Mercados de Capitais',
  BALM3: 'Equipamentos e Suprimentos Médicos',
  BALM4: 'Equipamentos e Suprimentos Médicos',
  B1AX34: 'Equipamentos e Suprimentos Médicos',
  BBRC11: 'Fundos de Investimento Imobiliário (FIIs)',
  RDPD11: 'Mercados de Capitais',
  RNDP11: 'Fundos de Investimento Hipotecários',
  BBFO11: 'Mercados de Capitais',
  BBSE3: 'Seguro',
  BBIM11: 'Mercados de Capitais',
  BBPO11: 'Fundos de Investimento Imobiliário (FIIs)',
  BILB34: '',
  BEWJ39: '',
  BOEI34: 'Espaço Aéreo e Defesa',
  CHVX34: 'Óleo, Gás e Combustíveis Consumíveis',
  IBMB34: 'Serviços de TI',
  UPSS34: 'Frete Aéreo e Logística',
  DHER34: 'Equipamentos e Suprimentos Médicos',
  KMBB34: 'Produtos domésticos',
  XRXB34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  DUKB34: 'Infraestrutura Elétrica',
  UPAC34: 'Rodovia e Ferrovia',
  FDMO34: 'Automóveis',
  ITLC34: 'Semicondutores e Equipamentos Associados',
  JNJB34: 'Produtos farmacêuticos',
  MSCD34: 'Serviços de TI',
  NIKE34: 'Têxteis, Vestuário e Produtos de Luxo',
  KHCB34: 'Produtos alimentícios',
  COWC34: 'Alimentos e Produtos Básicos de Consumo',
  GPSI34: 'Varejo Especializado',
  MACY34: 'Varejo Multilinha',
  ROST34: 'Varejo Especializado',
  DTCY3: 'Serviços Profissionais',
  R1MD34: 'Equipamentos e Suprimentos Médicos',
  FMXB34: 'Bebidas',
  M1TD34: 'Ferramentas e Serviços de Ciências da Vida',
  SIMN34: 'Fundos de Investimento Imobiliário (FIIs)',
  RDSA35: 'Óleo, Gás e Combustíveis Consumíveis',
  W1MG34: 'Entretenimento',
  Z1OM34: 'Software',
  N1VS34: 'Produtos farmacêuticos',
  SAPP34: 'Software',
  WGBA34: 'Alimentos e Produtos Básicos de Consumo',
  TGTB34: 'Varejo Multilinha',
  BOXP34: 'Fundos de Investimento Imobiliário (FIIs)',
  GPRO34: 'Bens domésticos duráveis',
  LBRN34: 'Varejo Especializado',
  TWTR34: 'Mídia e Serviços Interativos',
  SLBG34: 'Equipamentos e serviços de energia',
  BBYY34: 'Varejo Especializado',
  LMTB34: 'Espaço Aéreo e Defesa',
  MSFT34: '',
  PFIZ34: 'Produtos farmacêuticos',
  SBUB34: 'Hotéis, Restaurantes e Lazer',
  GDBR34: 'Espaço Aéreo e Defesa',
  HSHY34: 'Produtos alimentícios',
  E1WL34: 'Equipamentos e Suprimentos Médicos',
  TSMC34: 'Semicondutores e Equipamentos Associados',
  CATP34: 'Maquinário',
  DISB34: 'Entretenimento',
  EXXO34: 'Óleo, Gás e Combustíveis Consumíveis',
  HALI34: 'Equipamentos e serviços de energia',
  HPQB34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  ORCL34: 'Software',
  WFCO34: 'Bancos',
  WUNI34: 'Serviços de TI',
  LILY34: 'Produtos farmacêuticos',
  NFLX34: 'Entretenimento',
  BLAK34: 'Mercados de Capitais',
  CVSH34: 'Serviços e Fornecedores de Saúde',
  GILD34: 'Biotecnologia',
  SCHW34: 'Mercados de Capitais',
  W1BO34: 'Mídia e Serviços Interativos',
  CTGP34: '',
  GEOO34: 'Conglomerados Industriais',
  GSGI34: 'Mercados de Capitais',
  HOME34: 'Varejo Especializado',
  JPMC34: '',
  WALM34: 'Alimentos e Produtos Básicos de Consumo',
  BIIB34: 'Biotecnologia',
  CTSH34: 'Serviços de TI',
  SSFO34: 'Software',
  COLG34: 'Produtos domésticos',
  COTY34: 'Produtos pessoais',
  EBAY34: 'Internet e Varejo de Marketing Digital',
  MDLZ34: 'Produtos alimentícios',
  MOSC34: 'Químicos',
  RYTT34: 'Espaço Aéreo e Defesa',
  PAGS34: '',
  UBSG34: 'Mercados de Capitais',
  TSLA34: 'Automóveis',
  MELI34: 'Internet e Varejo de Marketing Digital',
  M1SC34: 'Mercados de Capitais',
  METB34: 'Seguro',
  BMYB34: 'Produtos farmacêuticos',
  FCXO34: 'Metais e Mineração',
  FDXB34: 'Frete Aéreo e Logística',
  QCOM34: 'Semicondutores e Equipamentos Associados',
  TEXA34: 'Semicondutores e Equipamentos Associados',
  COPH34: 'Óleo, Gás e Combustíveis Consumíveis',
  FBOK34: 'Mídia e Serviços Interativos',
  MCDC34: 'Hotéis, Restaurantes e Lazer',
  PEPB34: 'Bebidas',
  BERK34: 'Serviços Financeiros Diversificados',
  CMCS34: 'Mídia',
  COCA34: 'Bebidas',
  CSCO34: 'Equipamentos de Comunicação',
  MRCK34: 'Produtos farmacêuticos',
  PGCO34: 'Produtos domésticos',
  VERZ34: 'Serviços Diversificados de Telecomunicação',
  VISA34: '',
  HONB34: '',
  DDNB34: 'Químicos',
  GMCO34: 'Automóveis',
  FSLR34: '',
  MDTC34: 'Equipamentos e Suprimentos Médicos',
  RIGG34: 'Equipamentos e serviços de energia',
  TRVC34: 'Seguro',
  USSX34: 'Metais e Mineração',
  VLOE34: 'Óleo, Gás e Combustíveis Consumíveis',
  B1IL34: 'Entretenimento',
  B1PP34: 'Óleo, Gás e Combustíveis Consumíveis',
  N1OW34: 'Software',
  UNHH34: 'Serviços e Fornecedores de Saúde',
  R1IN34: 'Fundos de Investimento Imobiliário (FIIs)',
  RDSA34: 'Óleo, Gás e Combustíveis Consumíveis',
  SNEC34: 'Bens domésticos duráveis',
  ULEV34: 'Produtos pessoais',
  U1LT34: 'Varejo Especializado',
  B1GN34: 'Biotecnologia',
  BMOB3: 'Software e Programação',
  M1NS34: 'Bebidas',
  M1CB34: 'Bebidas',
  B2YN34: 'Produtos alimentícios',
  BHPG34: 'Metais e Mineração',
  BMKS3: 'Produtos de lazer',
  VITT3: '',
  B1MR34: 'Biotecnologia',
  Z1BH34: 'Equipamentos e Suprimentos Médicos',
  BIOM11: 'Biotecnologia',
  BIOM3: 'Biotecnologia',
  B1NT34: 'Biotecnologia',
  BSEV3: 'Processamento de Alimentos',
  T1CH34: 'Ferramentas e Serviços de Ciências da Vida',
  S1WK34: 'Maquinário',
  LLIS3: 'Têxteis, Vestuário e Produtos de Luxo',
  BLAU3: 'Biotecnologia e Medica',
  BITO39: '',
  HFOF11: 'Mercados de Capitais',
  H1RB34: 'Serviços Diversificados de Consumo',
  BLCP11: 'Mercados de Capitais',
  BLMO11: 'Mercados de Capitais',
  BLMG11: 'Mercados de Capitais',
  BLMR11: 'Mercados de Capitais',
  BNBR3: 'Bancos Regionais',
  RBBV11: 'Fundos de Investimento Imobiliário (FIIs)',
  SOJA3: 'Colheita',
  BOAS3: 'Serviços Profissionais',
  BOBR4: 'Produtos domésticos',
  BKNG34: 'Hotéis, Restaurantes e Lazer',
  B1WA34: 'Componentes Automotivos',
  B1SX34: 'Equipamentos e Suprimentos Médicos',
  BBRK3: 'Atividades Imobiliárias',
  RECT11: 'Mercados de Capitais',
  BRML3: 'Gestão e Desenvolvimento Imobiliário',
  BRPR3: 'Gestão e Desenvolvimento Imobiliário',
  MBRF11: 'Fundos de Investimento Imobiliário (FIIs)',
  BRBI11: '',
  BBDC3: 'Bancos Regionais',
  BBDC4: 'Bancos Regionais',
  BRAP4: 'Metais e Mineração',
  BRAP3: 'Metais e Mineração',
  FPAB11: 'Fundos de Investimento Imobiliário (FIIs)',
  MDIA3: 'Produtos alimentícios',
  CBOP11: 'Mercados de Capitais',
  C1AG34: 'Produtos alimentícios',
  N1WL34: 'Bens domésticos duráveis',
  F1BH34: 'Produtos de construção',
  CVCB3: 'Hotéis, Restaurantes e Lazer',
  HGBS11: 'Fundos de Investimento Imobiliário (FIIs)',
  IRBR3: 'Seguro',
  BPFF11: 'Fundos de Investimento Imobiliário (FIIs)',
  SANB4: 'Bancos Regionais',
  SANB3: 'Bancos Regionais',
  ENBR3: 'Infraestrutura Elétrica',
  LPSB3: 'Gestão e Desenvolvimento Imobiliário',
  FIIB11: 'Mercados de Capitais',
  MALL11: 'Mercados de Capitais',
  NCHB11: 'Mercados de Capitais',
  GSFI11: 'Mercados de Capitais',
  HBSA3: 'Marinho',
  OSXB3: 'Equipamentos e serviços de energia',
  SANB11: 'Bancos Regionais',
  EGIE3: 'Produtores de Eletricidade independentes e Energia Renovável',
  VIVT3: 'Serviços Diversificados de Telecomunicação',
  STBP3: 'Infraestrutura de Transportes',
  MERC4: 'Finanças de consumo',
  AGRO3: 'Produtos alimentícios',
  BRKM3: 'Fabricação de Produtos Químicos',
  BRKM5: 'Fabricação de Produtos Químicos',
  RBED11: 'Fundos de Investimento Imobiliário (FIIs)',
  RBIV11: 'Mercados de Capitais',
  RBRS11: 'Mercados de Capitais',
  RBVO11: 'Fundos de Investimento Hipotecários',
  SDIL11: 'Fundos de Investimento Imobiliário (FIIs)',
  RBVA11: 'Fundos de Investimento Imobiliário (FIIs)',
  RBFF11: 'Fundos de Investimento Imobiliário (FIIs)',
  RCRB11: 'Fundos de Investimento Imobiliário (FIIs)',
  CRFF11: 'Mercados de Capitais',
  CXRI11: 'Mercados de Capitais',
  BZLI11: 'Mercados de Capitais',
  BSLI4: 'Bancos',
  BREV11: 'Mercados de Capitais',
  IBFF11: 'Mercados de Capitais',
  BRCO11: 'Mercados de Capitais',
  BRFS3: 'Produtos alimentícios',
  ESTR4: 'Produtos de lazer',
  BRIM11: 'Mercados de Capitais',
  BPRP11: 'Mercados de Capitais',
  AVGO34: 'Semicondutores e Equipamentos Associados',
  B1RF34: 'Serviços de TI',
  B1FC34: 'Bebidas',
  BRZP11: 'Mercados de Capitais',
  BTLG11: 'Fundos de Investimento Imobiliário (FIIs)',
  BPML11: 'Mercados de Capitais',
  FEXC11: '',
  BRCR11: 'Fundos de Investimento Imobiliário (FIIs)',
  BTCR11: 'Mercados de Capitais',
  BDIV11: 'Mercados de Capitais',
  BPAC11: 'Mercados de Capitais',
  BCFF11: '',
  BKBR3: 'Hotéis, Restaurantes e Lazer',
  CEGR3: 'Infraestrutura de Gás',
  C1OG34: 'Óleo, Gás e Combustíveis Consumíveis',
  CEDO3: 'Têxteis, Vestuário e Produtos de Luxo',
  C1DN34: 'Software',
  CXSE3: 'Seguros (Vários)',
  CXTL11: 'Fundos de Investimento Imobiliário (FIIs)',
  CXCO11: '',
  HCAR3: '',
  CAMB3: 'Têxteis, Vestuário e Produtos de Luxo',
  CAML3: 'Produtos alimentícios',
  C1PB34: 'Produtos alimentícios',
  FCFL11: '',
  CNIC34: 'Rodovia e Ferrovia',
  CAJI34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  RBIR11: 'Mercados de Capitais',
  P1NW34: 'Infraestrutura Elétrica',
  RBGS11: 'Fundos de Investimento Imobiliário (FIIs)',
  RBCO11: 'Mercados de Capitais',
  RRCI11: '',
  RBRD11: 'Fundos de Investimento Imobiliário (FIIs)',
  MCCI11: 'Mercados de Capitais',
  RBDS11: 'Mercados de Capitais',
  RFOF11: 'Mercados de Capitais',
  CAON34: 'Finanças de consumo',
  CPFF11: 'Mercados de Capitais',
  CPTS11: 'Mercados de Capitais',
  HUSC11: 'Mercados de Capitais',
  CAPH34: 'Têxteis, Vestuário e Produtos de Luxo',
  C1AH34: 'Serviços e Fornecedores de Saúde',
  CARD3: 'Serviços de TI',
  R1CL34: 'Hotéis, Restaurantes e Lazer',
  SCAR3: 'Gestão e Desenvolvimento Imobiliário',
  K1MX34: 'Varejo Especializado',
  C1CL34: 'Hotéis, Restaurantes e Lazer',
  CRFB3: 'Alimentos e Produtos Básicos de Consumo',
  CASN3: 'Captação, Tratamento e Distribuição de Água',
  CASN4: 'Captação, Tratamento e Distribuição de Água',
  C1CI34: 'Fundos de Investimento Imobiliário (FIIs)',
  CLSC3: 'Infraestrutura Elétrica',
  C1BO34: 'Mercados de Capitais',
  C1BR34: 'Gestão e Desenvolvimento Imobiliário',
  CCPR3: 'Gestão e Desenvolvimento Imobiliário',
  CCRO3: 'Infraestrutura de Transportes',
  SADI11: 'Mercados de Capitais',
  HCTR11: 'Mercados de Capitais',
  CEBR3: 'Infraestrutura Elétrica',
  CEDO4: 'Têxteis, Vestuário e Produtos de Luxo',
  CEED3: 'Infraestrutura Elétrica',
  EEEL3: 'Infraestrutura Elétrica',
  CEED4: 'Infraestrutura Elétrica',
  C1NS34: 'Químicos',
  CLSC4: 'Infraestrutura Elétrica',
  GPAR3: 'Infraestrutura Elétrica',
  CEPE5: 'Infraestrutura Elétrica',
  RANI3: 'Papel e Produtos Florestais',
  MAPT3: 'Mercados de Capitais',
  MAPT4: 'Mercados de Capitais',
  CMIG4: 'Eléctricas',
  CMIG3: 'Eléctricas',
  CNES11: 'Mercados de Capitais',
  SBFG3: 'Comércio Varejista de Artigos do Vestuário',
  C1NC34: 'Serviços e Fornecedores de Saúde',
  PQDP11: 'Mercados de Capitais',
  C1NP34: 'Infraestrutura Variada',
  R1EG34: 'Fundos de Investimento Imobiliário (FIIs)',
  VISC11: 'Mercados de Capitais',
  CTXT11: 'Fundos de Investimento Imobiliário (FIIs)',
  L1MN34: 'Serviços Diversificados de Telecomunicação',
  C1ER34: 'Tecnologia de Saúde',
  CESP3: 'Produtores de Eletricidade independentes e Energia Renovável',
  CESP5: 'Produtores de Eletricidade independentes e Energia Renovável',
  CESP6: 'Produtores de Eletricidade independentes e Energia Renovável',
  C1FI34: 'Químicos',
  C1HR34: 'Frete Aéreo e Logística',
  CHCM34: 'Mídia',
  C1HK34: 'Software',
  C1HI34: 'Óleo, Gás e Combustíveis Consumíveis',
  E1MN34: 'Químicos',
  BCHI39: '',
  C1HL34: 'Serviços de Telecomunicação Sem Fio',
  C1MG34: 'Hotéis, Restaurantes e Lazer',
  C1BL34: 'Seguro',
  FSTU11: '',
  FSRF11: '',
  FNAM11: 'Mercados de Capitais',
  HGTX3: 'Têxteis, Vestuário e Produtos de Luxo',
  CIEL3: 'Serviços Financeiros ao Consumidor',
  C1IC34: 'Serviços e Fornecedores de Saúde',
  C1TA34: 'Serviços Comerciais & Suprimentos',
  C1FG34: 'Bancos',
  C1TX34: 'Software',
  K1CS34: 'Rodovia e Ferrovia',
  JFLL11: 'Mercados de Capitais',
  VVEO3: '',
  CHME34: 'Mercados de Capitais',
  C1MS34: 'Infraestrutura Variada',
  C1EO34: '',
  HOND34: 'Automóveis',
  H1PE34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  S1JM34: 'Produtos alimentícios',
  PTCH34: '',
  W1YC34: 'Fundos de Investimento Imobiliário (FIIs)',
  TAKP34: 'Produtos farmacêuticos',
  D1XC34: 'Serviços de TI',
  I1PC34: 'Contêineres e Embalagens',
  T1SO34: 'Infraestrutura Elétrica',
  E1MR34: 'Equipamentos Elétricos',
  V1MC34: 'Materiais de Construção',
  DEEC34: 'Maquinário',
  T1SC34: 'Varejo Especializado',
  G1PC34: 'Distribuidores',
  K1RC34: 'Alimentos e Produtos Básicos de Consumo',
  W1RK34: 'Contêineres e Embalagens',
  S1HW34: 'Químicos',
  CEEB3: 'Infraestrutura Elétrica',
  CEEB5: 'Infraestrutura Elétrica',
  COCE5: 'Infraestrutura Elétrica',
  COCE3: 'Infraestrutura Elétrica',
  COGN3: 'Educação',
  RCFF11: 'Mercados de Capitais',
  WLMM3: 'Empresas de Trading & Distribuidores',
  WLMM4: 'Empresas de Trading & Distribuidores',
  HAGA3: 'Produtos de construção',
  C1MA34: 'Bancos',
  CGAS5: 'Infraestrutura de Gás',
  CGAS3: 'Infraestrutura de Gás',
  CEOC11: 'Mercados de Capitais',
  S1BA34: 'Fundos de Investimento Imobiliário (FIIs)',
  CPLE11: 'Infraestrutura Elétrica',
  MSPA3: 'Mídia',
  CPLE5: 'Infraestrutura Elétrica',
  W1MB34: 'Óleo, Gás e Combustíveis Consumíveis',
  M1MC34: '',
  C1OO34: 'Equipamentos e Suprimentos Médicos',
  ELCI34: 'Produtos pessoais',
  LOWC34: 'Varejo Especializado',
  I1PH34: 'Mídia',
  P1RG34: 'Produtos farmacêuticos',
  T1EL34: 'Equipamentos, Instrumentos e Componentes Eletrônicos',
  FCCQ11: 'Mercados de Capitais',
  E1DI34: 'Infraestrutura Variada',
  CURY3: 'Serviços de Construção',
  FLMA11: 'Mercados de Capitais',
  J1CI34: 'Produtos de construção',
  C1PR34: 'Serviços Comerciais & Suprimentos',
  CSMG3: 'Captação, Tratamento e Distribuição de Água',
  CPLE3: 'Infraestrutura Elétrica',
  PICE11: 'Mercados de Capitais',
  G1LW34: 'Equipamentos, Instrumentos e Componentes Eletrônicos',
  THRA11: '',
  VLOL11: 'Fundos de Investimento Imobiliário (FIIs)',
  XPCM11: 'Fundos de Investimento Imobiliário (FIIs)',
  PATC11: 'Mercados de Capitais',
  XTED11: 'Fundos de Investimento Imobiliário (FIIs)',
  CORR4: 'Gestão e Desenvolvimento Imobiliário',
  RLOG3: 'Ferroviária',
  CSAN3: 'Óleo, Gás e Combustíveis Consumíveis',
  CSRN3: 'Infraestrutura Elétrica',
  CTNM4: 'Têxteis, Vestuário e Produtos de Luxo',
  CTNM3: 'Têxteis, Vestuário e Produtos de Luxo',
  GGRC11: 'Mercados de Capitais',
  LOGG3: 'Gestão e Desenvolvimento Imobiliário',
  CPFE3: 'Infraestrutura Elétrica',
  CRDE3: 'Gestão e Desenvolvimento Imobiliário',
  QAMI11: '',
  IFRA11: 'Mercados de Capitais',
  HGIC11: 'Mercados de Capitais',
  CRHP34: 'Materiais de Construção',
  CVBI11: 'Mercados de Capitais',
  KNHY11: 'Mercados de Capitais',
  VGIP11: 'Mercados de Capitais',
  HCRI11: '',
  CRPG3: 'Químicos',
  CRPG5: 'Químicos',
  CRPG6: 'Químicos',
  N1CL34: 'Hotéis, Restaurantes e Lazer',
  CSED3: 'Serviços Diversificados de Consumo',
  XPCI11: 'Mercados de Capitais',
  RBRY11: 'Mercados de Capitais',
  HGRE11: 'Fundos de Investimento Imobiliário (FIIs)',
  HGCR11: 'Mercados de Capitais',
  HGPO11: 'Mercados de Capitais',
  HGLG11: 'Fundos de Investimento Imobiliário (FIIs)',
  HGFF11: 'Mercados de Capitais',
  HGRU11: 'Mercados de Capitais',
  CMIN3: 'Metais e Mineração',
  CSNA3: 'Metais e Mineração',
  CSXC34: 'Rodovia e Ferrovia',
  TRPL4: 'Infraestrutura Elétrica',
  TRPL3: 'Infraestrutura Elétrica',
  C1MI34: 'Maquinário',
  CVCB3T: '',
  IFCM3: '',
  CYRE3: 'Bens domésticos duráveis',
  IFID11: 'Mercados de Capitais',
  RDOR3: 'Serviços e Fornecedores de Saúde',
  D1HI34: 'Bens domésticos duráveis',
  DMVF3: 'Alimentos e Produtos Básicos de Consumo',
  HMOC11: '',
  D1RI34: 'Hotéis, Restaurantes e Lazer',
  DASA3: 'Estabelecimentos de Saúde',
  H1OG34: 'Automóveis',
  EQPA3: 'Infraestrutura Elétrica',
  EQPA5: 'Infraestrutura Elétrica',
  OUFF11: 'Mercados de Capitais',
  KNIP11: 'Mercados de Capitais',
  KDIF11: 'Mercados de Capitais',
  HREC11: 'Mercados de Capitais',
  RECX11: 'Mercados de Capitais',
  MGFF11: 'Mercados de Capitais',
  FNOR11: 'Mercados de Capitais',
  SNFF11: '',
  GCFF11: 'Mercados de Capitais',
  NSLU11: 'Mercados de Capitais',
  PLOG11: 'Mercados de Capitais',
  MATD3: 'Serviços e Fornecedores de Saúde',
  D1EL34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  HCST11: 'Mercados de Capitais',
  MFII11: 'Fundos de Investimento Imobiliário (FIIs)',
  MFAI11: 'Mercados de Capitais',
  ORPD11: 'Mercados de Capitais',
  T2TD34: '',
  DEVA11: 'Mercados de Capitais',
  HRDF11: 'Mercados de Capitais',
  D1VN34: '',
  DEXP3: 'Fabricação de Produtos Químicos',
  DEXP4: 'Fabricação de Produtos Químicos',
  DEOP34: 'Bebidas',
  Q1UE34: 'Serviços e Fornecedores de Saúde',
  F1AN34: 'Óleo, Gás e Combustíveis Consumíveis',
  D1LR34: 'Fundos de Investimento Imobiliário (FIIs)',
  W1DC34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  PNVL3: 'Alimentos e Produtos Básicos de Consumo',
  PNVL4: 'Alimentos e Produtos Básicos de Consumo',
  DIRR3: 'Bens domésticos duráveis',
  D1FS34: 'Finanças de consumo',
  DCVY35: 'Mídia',
  D1IS34: 'Mídia',
  BRDT3: 'Varejo Especializado',
  EQPA7: 'Infraestrutura Elétrica',
  BIYW39: '',
  D1OC34: 'Software',
  DOHL3: 'Têxteis, Vestuário e Produtos de Luxo',
  DOHL4: 'Têxteis, Vestuário e Produtos de Luxo',
  DGCO34: 'Varejo Multilinha',
  HPDP11: 'Mercados de Capitais',
  FISD11: 'Mercados de Capitais',
  D1OM34: 'Infraestrutura Variada',
  DMMO11: '',
  DMMO3: 'Óleo, Gás e Combustíveis Consumíveis',
  DMMO3T: '',
  DOTZ3: '',
  D1OV34: 'Maquinário',
  SPTW11: 'Fundos de Investimento Imobiliário (FIIs)',
  WSON33: 'Infraestrutura de Transportes',
  RADL3: 'Alimentos e Produtos Básicos de Consumo',
  D1TE34: 'Infraestrutura Variada',
  MDNE3: 'Gestão e Desenvolvimento Imobiliário',
  D1RE34: 'Fundos de Investimento Imobiliário (FIIs)',
  DTEX3: 'Construção - Suprimentos e Acessórios',
  IFIE11: 'Mercados de Capitais',
  GGPS3: 'Serviços Comerciais & Suprimentos',
  E1TN34: 'Equipamentos Elétricos',
  E1CL34: 'Químicos',
  E1CO34: 'Óleo, Gás e Combustíveis Consumíveis',
  ECOR3: 'Infraestrutura de Transportes',
  EDGA11: 'Fundos de Investimento Imobiliário (FIIs)',
  E1IX34: 'Infraestrutura Elétrica',
  SEER3: 'Serviços Diversificados de Consumo',
  SEER3T: '',
  TORD11: 'Mercados de Capitais',
  EKTR4: 'Infraestrutura Elétrica',
  EKTR3: 'Infraestrutura Elétrica',
  ELET6: 'Eléctricas',
  ELET3: 'Eléctricas',
  LIPR3: 'Infraestrutura Elétrica',
  ELMD3: 'Mídia',
  EMAE4: 'Produtores de Eletricidade independentes e Energia Renovável',
  EMBR3: 'Espaço Aéreo e Defesa',
  ENAT3: 'Óleo, Gás e Combustíveis Consumíveis',
  ECPR3: 'Têxteis, Vestuário e Produtos de Luxo',
  VIGT11: 'Mercados de Capitais',
  REDE3: 'Infraestrutura Elétrica',
  GEPA3: 'Infraestrutura Elétrica',
  GEPA4: 'Infraestrutura Elétrica',
  POWE3: 'Produtores de Eletricidade independentes e Energia Renovável',
  ENMT4: 'Infraestrutura Elétrica',
  ENGI4: 'Infraestrutura Elétrica',
  ENGI11: 'Infraestrutura Elétrica',
  ENGI3: 'Infraestrutura Elétrica',
  ENMT3: 'Infraestrutura Elétrica',
  NEXT34: 'Infraestrutura Elétrica',
  X1EL34: 'Infraestrutura Elétrica',
  S1RE34: 'Infraestrutura Variada',
  W1EC34: 'Infraestrutura Variada',
  N1RG34: 'Infraestrutura Elétrica',
  ENEV3: 'Produtores de Eletricidade independentes e Energia Renovável',
  J1EG34: 'Serviços Profissionais',
  ENJU3: 'Internet e Varejo de Marketing Digital',
  E1TR34: 'Infraestrutura Elétrica',
  P1EG34: 'Infraestrutura Variada',
  E1OG34: 'Óleo, Gás e Combustíveis Consumíveis',
  EQTL3: 'Infraestrutura Elétrica',
  E1FX34: 'Serviços Profissionais',
  EQIX34: 'Fundos de Investimento Imobiliário (FIIs)',
  KNRE11: 'Fundos de Investimento Imobiliário (FIIs)',
  E1QR34: 'Fundos de Investimento Imobiliário (FIIs)',
  E1RI34: 'Equipamentos de Comunicação',
  ESPA3: 'Serviços Diversificados de Consumo',
  E1SS34: 'Fundos de Investimento Imobiliário (FIIs)',
  EEEL4: 'Infraestrutura Elétrica',
  MORE11: 'Mercados de Capitais',
  JSRE11: 'Fundos de Investimento Imobiliário (FIIs)',
  TRXB11: 'Mercados de Capitais',
  OURE11: 'Mercados de Capitais',
  ETER3: 'Materiais de Construção',
  BEZU39: '',
  EUCA4: 'Papel e Produtos Florestais',
  EUCA3: 'Papel e Produtos Florestais',
  EURO11: 'Mercados de Capitais',
  KEVE11: 'Mercados de Capitais',
  KINP11: 'Mercados de Capitais',
  EVEN3: 'Serviços de Construção',
  E1VE34: 'Seguro',
  E1VR34: 'Infraestrutura Elétrica',
  E1SE34: 'Infraestrutura Elétrica',
  I1CE34: 'Mercados de Capitais',
  E1XC34: 'Infraestrutura Elétrica',
  EXGR34: 'Hotéis, Restaurantes e Lazer',
  E1XP34: 'Frete Aéreo e Logística',
  E1XR34: 'Fundos de Investimento Imobiliário (FIIs)',
  EZTC3: 'Bens domésticos duráveis',
  F1FI34: 'Equipamentos de Comunicação',
  VRTA11: 'Fundos de Investimento Hipotecários',
  F1RI34: 'Fundos de Investimento Imobiliário (FIIs)',
  FHER3: 'Químicos',
  FESA4: 'Metais e Mineração',
  FESA3: 'Metais e Mineração',
  SFND11: 'Fundos de Investimento Imobiliário (FIIs)',
  F1NI34: 'Serviços de TI',
  TFCO4: 'Varejo Especializado',
  G1FI34: 'Metais e Mineração',
  KNCR11: 'Fundos de Investimento Hipotecários',
  NEWU11: 'Fundos de Investimento Imobiliário (FIIs)',
  SHPH11: 'Mercados de Capitais',
  SCPF11: 'Mercados de Capitais',
  HTMX11: 'Mercados de Capitais',
  XPLG11: 'Mercados de Capitais',
  LVBI11: '',
  VTLT11: 'Mercados de Capitais',
  DMAC11: 'Mercados de Capitais',
  VINO11: 'Mercados de Capitais',
  HLOG11: 'Mercados de Capitais',
  FPNG11: 'Mercados de Capitais',
  RCFA11: '',
  MGHT11: 'Mercados de Capitais',
  LASC11: 'Mercados de Capitais',
  VSEC11: 'Mercados de Capitais',
  URPR11: 'Mercados de Capitais',
  MGCR11: 'Mercados de Capitais',
  RELG11: 'Mercados de Capitais',
  OUJP11: 'Mercados de Capitais',
  VGIR11: 'Mercados de Capitais',
  VILG11: 'Mercados de Capitais',
  XPIN11: 'Mercados de Capitais',
  FIVN11: 'Mercados de Capitais',
  FLRP11: '',
  MAXR11: 'Mercados de Capitais',
  TRNT11: '',
  ONEF11: 'Mercados de Capitais',
  RNGO11: 'Fundos de Investimento Imobiliário (FIIs)',
  HABT11: 'Mercados de Capitais',
  NPAR11: 'Mercados de Capitais',
  RBRP11: 'Mercados de Capitais',
  REIT11: 'Mercados de Capitais',
  LGCP11: 'Mercados de Capitais',
  VVPR11: '',
  SPAF11: 'Mercados de Capitais',
  ARRI11: 'Mercados de Capitais',
  RBRL11: 'Mercados de Capitais',
  HOSI11: 'Mercados de Capitais',
  SEQR11: 'Mercados de Capitais',
  ABCP11: 'Mercados de Capitais',
  KNRI11: 'Fundos de Investimento Imobiliário (FIIs)',
  FMOF11: 'Mercados de Capitais',
  PLRI11: 'Mercados de Capitais',
  JRDM11: 'Fundos de Investimento Imobiliário (FIIs)',
  VSHO11: 'Fundos de Investimento Imobiliário (FIIs)',
  KFOF11: 'Mercados de Capitais',
  GTWR11: 'Mercados de Capitais',
  FVPQ11: 'Mercados de Capitais',
  HBRH11: 'Mercados de Capitais',
  GALG11: 'Mercados de Capitais',
  WPLZ11: 'Mercados de Capitais',
  HSML11: 'Mercados de Capitais',
  TORM13: 'Mercados de Capitais',
  LUGG11: 'Mercados de Capitais',
  SARE11: 'Mercados de Capitais',
  VIUR11: '',
  MXRF11: 'Fundos de Investimento Hipotecários',
  PRSV11: 'Fundos de Investimento Imobiliário (FIIs)',
  VGHF11: 'Mercados de Capitais',
  RMAI11: '',
  HSLG11: 'Mercados de Capitais',
  PORD11: 'Fundos de Investimento Imobiliário (FIIs)',
  XPML11: '',
  RBRR11: 'Mercados de Capitais',
  TOUR11: 'Mercados de Capitais',
  XPPR11: 'Mercados de Capitais',
  VOTS11: 'Mercados de Capitais',
  BICR11: 'Mercados de Capitais',
  RZTR11: 'Mercados de Capitais',
  RECR11: 'Mercados de Capitais',
  IRDM11: 'Mercados de Capitais',
  FSPE11: 'Mercados de Capitais',
  PABY11: 'Fundos de Investimento Imobiliário (FIIs)',
  KNSC11: 'Mercados de Capitais',
  QIFF11: 'Mercados de Capitais',
  LFTT11: 'Mercados de Capitais',
  TRXF11: 'Mercados de Capitais',
  RVBI11: 'Mercados de Capitais',
  J1EF34: '',
  P1FG34: 'Seguro',
  R1FC34: 'Bancos',
  R1JF34: 'Mercados de Capitais',
  H1IG34: 'Seguro',
  M1UF34: 'Bancos',
  PNCS34: 'Bancos',
  S1IV34: 'Bancos',
  B1BT34: 'Bancos',
  S1YF34: 'Finanças de consumo',
  P1BC34: 'Bancos',
  OFSA3: 'Produtos farmacêuticos',
  XPOM11: '',
  XPIE11: 'Mercados de Capitais',
  PFIN11: 'Mercados de Capitais',
  F1EC34: 'Infraestrutura Elétrica',
  F1IS34: 'Serviços de TI',
  TMOS34: 'Ferramentas e Serviços de Ciências da Vida',
  I1FF34: 'Químicos',
  FLTC34: 'Serviços de TI',
  FLRY3: 'Serviços e Fornecedores de Saúde',
  F1LI34: '',
  F1LS34: 'Maquinário',
  F1MC34: 'Químicos',
  H1RL34: 'Produtos alimentícios',
  SHOW3: 'Atividades de Recreação e Lazer',
  JFEN3: 'Gestão e Desenvolvimento Imobiliário',
  F1TN34: 'Software',
  F1TV34: 'Maquinário',
  FOXC34: 'Mídia',
  F1RA34: 'Mercados de Capitais',
  FRAS3: 'Componentes Automotivos',
  HUSI11: 'Mercados de Capitais',
  G2DI33: '',
  GFSA3: 'Bens domésticos duráveis',
  G1RM34: 'Bens domésticos duráveis',
  G1AR34: 'Serviços de TI',
  G1DS34: 'Serviços de TI',
  G1MI34: 'Produtos alimentícios',
  GSHP3: 'Atividades Imobiliárias',
  GPRK34: 'Óleo, Gás e Combustíveis Consumíveis',
  OMGE3: 'Produtores de Eletricidade independentes e Energia Renovável',
  GGBR4: 'Ferro e Aço',
  GGBR3: 'Ferro e Aço',
  GOAU3: 'Metais e Mineração',
  GOAU4: 'Metais e Mineração',
  NINJ3: '',
  G1SK34: 'Produtos farmacêuticos',
  L1BT34: 'Serviços Diversificados de Telecomunicação',
  G1PI34: 'Serviços de TI',
  G1LL34: 'Seguro',
  GOLL11: 'Companhias Aéreas',
  GOLL12: 'Companhias Aéreas',
  GOLL4: 'Companhias Aéreas',
  BIAU39: '',
  G1WW34: 'Empresas de Trading & Distribuidores',
  CGRA3: 'Varejo Multilinha',
  CGRA4: 'Varejo Multilinha',
  S1LG34: 'Fundos de Investimento Imobiliário (FIIs)',
  GRND3: 'Têxteis, Vestuário e Produtos de Luxo',
  INGG34: 'Bancos',
  T1RO34: 'Mercados de Capitais',
  U1NM34: 'Seguro',
  CRIP34: 'Internet e Varejo de Marketing Digital',
  O1MC34: 'Mídia',
  H1TH34: 'Hotéis, Restaurantes e Lazer',
  V1OD34: 'Serviços de Telecomunicação Sem Fio',
  NOCG34: 'Espaço Aéreo e Defesa',
  SOMA3: 'Têxteis, Vestuário e Produtos de Luxo',
  GMAT3: 'Alimentos e Produtos Básicos de Consumo',
  GUAR3: 'Têxteis, Vestuário e Produtos de Luxo',
  HBTS5: 'Conglomerados Industriais',
  HAGA4: 'Produtos de construção',
  R1HI34: 'Serviços Profissionais',
  H1BI34: 'Têxteis, Vestuário e Produtos de Luxo',
  HAPV3: 'Serviços e Fornecedores de Saúde',
  H1AS34: 'Produtos de lazer',
  HBRE3: 'Gestão e Desenvolvimento Imobiliário',
  H1CA34: 'Serviços e Fornecedores de Saúde',
  U1HS34: 'Serviços e Fornecedores de Saúde',
  P1EA34: 'Fundos de Investimento Imobiliário (FIIs)',
  HBOR3: 'Gestão e Desenvolvimento Imobiliário',
  H1SI34: 'Serviços e Fornecedores de Saúde',
  HETA4: 'Bens domésticos duráveis',
  PARD3: 'Estabelecimentos de Saúde',
  H1ES34: 'Óleo, Gás e Combustíveis Consumíveis',
  H1LT34: 'Hotéis, Restaurantes e Lazer',
  R1YA34: 'Companhias Aéreas',
  H1SB34: 'Bancos',
  I1QV34: 'Ferramentas e Serviços de Ciências da Vida',
  N1LS34: 'Serviços Profissionais',
  NMRH34: 'Mercados de Capitais',
  PYPL34: 'Serviços de TI',
  M1KT34: 'Mercados de Capitais',
  V1IP34: 'Internet e Varejo de Marketing Digital',
  L1WH34: 'Produtos alimentícios',
  H1FC34: 'Óleo, Gás e Combustíveis Consumíveis',
  H1OL34: 'Equipamentos e Suprimentos Médicos',
  H1ST34: 'Fundos de Investimento Imobiliário (FIIs)',
  HOOT4: 'Hotéis, Restaurantes e Lazer',
  H1UM34: 'Serviços e Fornecedores de Saúde',
  H1II34: 'Espaço Aéreo e Defesa',
  HYPE3: 'Produtos farmacêuticos',
  I1DX34: 'Equipamentos e Suprimentos Médicos',
  IGBR3: 'Gestão e Desenvolvimento Imobiliário',
  MTIG4: 'Contêineres e Embalagens',
  IGTA3: 'Gestão e Desenvolvimento Imobiliário',
  I1NF34: 'Serviços Profissionais',
  I1TW34: 'Maquinário',
  I1LM34: 'Ferramentas e Serviços de Ciências da Vida',
  MEAL3: 'Hotéis, Restaurantes e Lazer',
  VSLH11: 'Mercados de Capitais',
  LOGN3: 'Marinho',
  I1NC34: 'Biotecnologia',
  ROMI3: 'Maquinário',
  PRNR3: 'Serviços Comerciais & Suprimentos',
  L1YB34: 'Químicos',
  M1HK34: 'Bens domésticos duráveis',
  P1PG34: 'Químicos',
  INEP4: 'Equipamentos Elétricos',
  INEP3: 'Equipamentos Elétricos',
  POSI3: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  GENT3: '',
  I1FO34: '',
  M1XI34: 'Semicondutores e Equipamentos Associados',
  INTB3: 'Equipamentos de Comunicação',
  T1TW34: 'Entretenimento',
  GNDI3: 'Serviços e Fornecedores de Saúde',
  M1GM34: 'Hotéis, Restaurantes e Lazer',
  PHMO34: 'Tabaco',
  INTU34: 'Software',
  I1SR34: 'Equipamentos e Suprimentos Médicos',
  I1VZ34: 'Mercados de Capitais',
  LUXM4: 'Marinho',
  MYPK3: 'Maquinário',
  I1PG34: 'Equipamentos, Instrumentos e Componentes Eletrônicos',
  I1RM34: 'Fundos de Investimento Imobiliário (FIIs)',
  BSLV39: 'Mercados de Capitais',
  ITUB3: 'Bancos Regionais',
  ITUB4: 'Bancos Regionais',
  ITSA4: 'Bancos',
  ITSA3: 'Bancos',
  JALL3: 'Produtos alimentícios',
  JBSS3: 'Processamento de Alimentos',
  JDCO34: 'Internet e Varejo de Marketing Digital',
  JPSA3: 'Gestão e Desenvolvimento Imobiliário',
  JHSF3: 'Gestão e Desenvolvimento Imobiliário',
  JOPA4: 'Produtos alimentícios',
  JOPA3: 'Produtos alimentícios',
  JSLG3: 'Rodovia e Ferrovia',
  J1NP34: 'Equipamentos de Comunicação',
  VCJR11: 'Mercados de Capitais',
  CTKA4: 'Têxteis, Vestuário e Produtos de Luxo',
  CTKA3: 'Têxteis, Vestuário e Produtos de Luxo',
  K1EL34: 'Produtos alimentícios',
  KEPL3: 'Maquinário',
  KEPL11: 'Maquinário',
  K1EY34: 'Bancos',
  K1SG34: 'Equipamentos, Instrumentos e Componentes Eletrônicos',
  K1IM34: 'Fundos de Investimento Imobiliário (FIIs)',
  KMIC34: 'Óleo, Gás e Combustíveis Consumíveis',
  K1LA34: 'Semicondutores e Equipamentos Associados',
  KLBN4: 'Papel e Produtos de Papel',
  KLBN11: 'Papel e Produtos de Papel',
  KLBN3: 'Papel e Produtos de Papel',
  K1SS34: 'Varejo Multilinha',
  PHGN34: 'Equipamentos e Suprimentos Médicos',
  KRSA3: '',
  L1HX34: 'Espaço Aéreo e Defesa',
  L1CA34: 'Serviços e Fornecedores de Saúde',
  L1RC34: 'Semicondutores e Equipamentos Associados',
  R1LC34: 'Têxteis, Vestuário e Produtos de Luxo',
  LAVV3: 'Gestão e Desenvolvimento Imobiliário',
  L1EG34: 'Bens domésticos duráveis',
  L1EN34: 'Bens domésticos duráveis',
  LEVE3: 'Componentes Automotivos',
  LSXM35: 'Entretenimento',
  LSXM34: '',
  LMED3: 'Equipamentos e Suprimentos Médicos',
  LIGT3: 'Infraestrutura Elétrica',
  L1NC34: 'Seguro',
  L1IN34: 'Químicos',
  LINX3: 'Software e Programação',
  L1KQ34: 'Distribuidores',
  RENT3: 'Rodovia e Ferrovia',
  LCAM3: 'Rodovia e Ferrovia',
  LWSA3: 'Serviços de TI',
  L1OE34: 'Seguro',
  OULG11: 'Fundos de Investimento Imobiliário (FIIs)',
  LREN3: 'Varejo Multilinha',
  AMAR3: 'Varejo Multilinha',
  LJQQ3: 'Varejo Especializado',
  MGLU3: 'Varejo Multilinha',
  L1UL34: 'Têxteis, Vestuário e Produtos de Luxo',
  LUPA3: 'Equipamentos e serviços de energia',
  W1MC34: 'Serviços Comerciais & Suprimentos',
  MGEL4: 'Componentes Automotivos',
  RPMG3: 'Óleo, Gás e Combustíveis Consumíveis',
  M1RO34: 'Óleo, Gás e Combustíveis Consumíveis',
  M1PC34: 'Óleo, Gás e Combustíveis Consumíveis',
  POMO4: 'Maquinário',
  POMO3: 'Maquinário',
  MRFG3: 'Produtos alimentícios',
  M1LM34: 'Materiais de Construção',
  MKLC34: 'Seguro',
  M1TT34: 'Hotéis, Restaurantes e Lazer',
  SMTO3: 'Processamento de Alimentos',
  M1AS34: 'Produtos de construção',
  M1KC34: 'Produtos alimentícios',
  M1CK34: 'Serviços e Fornecedores de Saúde',
  BDLL3: 'Maquinário',
  V1AR34: '',
  MSPA4: 'Mídia',
  MELK3: 'Gestão e Desenvolvimento Imobiliário',
  PGMN3: 'Alimentos e Produtos Básicos de Consumo',
  FRIO3: 'Maquinário',
  MTSA3: 'Maquinário',
  NORD3: 'Maquinário',
  RSUL4: 'Maquinário',
  MTSA4: 'Maquinário',
  M1CH34: 'Semicondutores e Equipamentos Associados',
  MUTC34: 'Semicondutores e Equipamentos Associados',
  MILS3: 'Empresas de Trading & Distribuidores',
  BEEF3: 'Produtos alimentícios',
  BEEF11: 'Produtos alimentícios',
  MNPR3: 'Produtos alimentícios',
  MTRE3: 'Serviços de Construção',
  MMXM3: 'Metais e Mineração',
  MMXM11: 'Metais e Mineração',
  MBLY3: 'Internet e Varejo de Marketing Digital',
  M1RN34: 'Biotecnologia',
  MCOR34: 'Mercados de Capitais',
  MOSI3: 'Mídia e Serviços Interativos',
  TMCO34: 'Automóveis',
  M1SI34: 'Equipamentos de Comunicação',
  MOVI3: 'Rodovia e Ferrovia',
  MRVE3: 'Bens domésticos duráveis',
  MULT3: 'Gestão e Desenvolvimento Imobiliário',
  MNDL3: 'Bens domésticos duráveis',
  CASH3: 'Mídia e Serviços Interativos',
  N1DA34: 'Mercados de Capitais',
  N1OV34: 'Equipamentos e serviços de energia',
  NTCO3: 'Produtos pessoais',
  P1IO34: 'Óleo, Gás e Combustíveis Consumíveis',
  NEOE3: 'Infraestrutura Elétrica',
  NGRD3: 'Software',
  N1TA34: 'Hardware, Armazenamento e Periféricos de Tecnologia',
  NETE34: 'Entretenimento',
  N1EM34: 'Metais e Mineração',
  N1WS34: 'Mídia',
  N1IS34: 'Infraestrutura Variada',
  J1WN34: 'Varejo Multilinha',
  N1SC34: 'Rodovia e Ferrovia',
  N1TR34: '',
  S1YM34: '',
  N1UE34: 'Metais e Mineração',
  NUTR3: 'Químicos',
  N1XP34: 'Semicondutores e Equipamentos Associados',
  NVDC34: 'Semicondutores e Equipamentos Associados',
  N1VR34: 'Bens domésticos duráveis',
  OXYP34: 'Óleo, Gás e Combustíveis Consumíveis',
  OPCT3: 'Serviços Comerciais & Suprimentos',
  ODPV3: 'Estabelecimentos de Saúde',
  OIBR3: 'Serviços de Comunicações',
  OIBR4: 'Serviços de Comunicações',
  PRIO3: 'Óleo, Gás e Combustíveis Consumíveis',
  PDTC3: 'Equipamento de Comunicações',
  PLAS3: 'Componentes Automotivos',
  FRTA3: 'Produtos alimentícios',
  TPIS3: 'Infraestrutura de Transportes',
  UGPA3: 'Extração de Petróleo e Gás natural',
  VLID3: 'Serviços Comerciais & Suprimentos',
  TUPY3: 'Componentes Automotivos',
  UCAS3: 'Bens domésticos duráveis',
  CTSA3: 'Têxteis, Vestuário e Produtos de Luxo',
  VULC3: 'Calçados',
  PETZ3: 'Varejo Especializado',
  ORVR3: 'Serviços Comerciais & Suprimentos',
  RAIL3: 'Rodovia e Ferrovia',
  QUAL3: 'Serviços e Fornecedores de Saúde',
  RAPT3: 'Maquinário',
  RSID3: 'Bens domésticos duráveis',
  TECN3: 'Têxteis, Vestuário e Produtos de Luxo',
  SEQL3: 'Frete Aéreo e Logística',
  RCSL3: 'Maquinário',
  SLED3: 'Varejo Especializado',
  SUZB3: 'Papel e Produtos Florestais',
  RDNI3: 'Serviços de Construção',
  SGPS3: 'Bens domésticos duráveis',
  TCSA3: 'Bens domésticos duráveis',
  TGMA3: 'Rodovia e Ferrovia',
  TOTS3: 'Software',
  TRIS3: 'Bens domésticos duráveis',
  VIVR3: 'Bens domésticos duráveis',
  SQIA3: 'Software',
  AHEB3: 'Hotéis, Restaurantes e Lazer',
  SAPR3: 'Captação, Tratamento e Distribuição de Água',
  WEST3: 'Mobiliária e Acessórios',
  SIMH3: 'Rodovia e Ferrovia',
  PDGR3: 'Bens domésticos duráveis',
  PFRM3: 'Serviços e Fornecedores de Saúde',
  PSSA3: 'Seguro',
  SBSP3: 'Captação, Tratamento e Distribuição de Água',
  TIMS3: 'Serviços de Comunicações',
  TESA3: 'Produtos alimentícios',
  TCNO3: 'Construção e Engenharia',
  WIZS3: 'Seguro',
  WHRL3: 'Bens domésticos duráveis',
  TELB3: 'Serviços Diversificados de Telecomunicação',
  VVAR3: 'Comércio Varejista Especializado',
  SMLS3: 'Mídia',
  VAMO3: 'Rodovia e Ferrovia',
  PETR3: 'Extração de Petróleo e Gás natural',
  PMAM3: 'Extração de Minerais Metálicos',
  PTBL3: 'Produtos de construção',
  UNIP3: 'Químicos',
  USIM3: 'Metais e Mineração',
  VALE3: 'Metais e Mineração',
  WEGE3: 'Equipamentos Elétricos',
  RNEW3: 'Produtores de Eletricidade independentes e Energia Renovável',
  TEND3: 'Atividades Imobiliárias',
  PLPL3: 'Bens domésticos duráveis',
  O1KE34: 'Óleo, Gás e Combustíveis Consumíveis',
  P1AC34: 'Maquinário',
  P1KG34: 'Contêineres e Embalagens',
  PATI3: 'Metais e Mineração',
  PATI4: 'Metais e Mineração',
  P1HC34: 'Maquinário',
  RAPT4: 'Maquinário',
  YDUQ3: 'Serviços Diversificados de Consumo',
  P1AY34: 'Serviços de TI',
  P1YC34: '',
  P1NR34: 'Maquinário',
  P1KI34: 'Ferramentas e Serviços de Ciências da Vida',
  PETR4: 'Extração de Petróleo e Gás natural',
  RECV3: '',
  PTNT4: 'Têxteis, Vestuário e Produtos de Luxo',
  PTNT3: 'Têxteis, Vestuário e Produtos de Luxo',
  PINE4: 'Bancos Regionais',
  SAPR4: 'Captação, Tratamento e Distribuição de Água',
  RCSL4: 'Maquinário',
  SMLS3T: '',
  TAEE4: 'Eléctricas',
  TEKA4: 'Têxteis, Vestuário e Produtos de Luxo',
  TELB4: 'Serviços Diversificados de Telecomunicação',
  MWET4: 'Componentes Automotivos',
  TCNO4: 'Construção e Engenharia',
  TXRX4: 'Têxteis, Vestuário e Produtos de Luxo',
  CTSA4: 'Têxteis, Vestuário e Produtos de Luxo',
  WHRL4: 'Bens domésticos duráveis',
  SHUL4: 'Maquinário',
  RNEW4: 'Produtores de Eletricidade independentes e Energia Renovável',
  TEKA3: 'Têxteis, Vestuário e Produtos de Luxo',
  UNIP5: 'Químicos',
  AHEB5: 'Hotéis, Restaurantes e Lazer',
  USIM5: 'Metais e Mineração',
  SOND5: 'Construção e Engenharia',
  SOND6: 'Construção e Engenharia',
  UNIP6: 'Químicos',
  USIM6: 'Metais e Mineração',
  SNSY5: 'Químicos',
  PSVM11: 'Infraestrutura de Transportes',
  P1PL34: 'Infraestrutura Elétrica',
  PPLA11: 'Mercados de Capitais',
  TKNO4: 'Metais e Mineração',
  P1GR34: 'Seguro',
  P1LD34: 'Fundos de Investimento Imobiliário (FIIs)',
  TEPP11: 'Mercados de Capitais',
  P1DT34: 'Seguro',
  P1SA34: 'Fundos de Investimento Imobiliário (FIIs)',
  P1HM34: 'Bens domésticos duráveis',
  P1VH34: 'Têxteis, Vestuário e Produtos de Luxo',
  Q1RV34: 'Semicondutores e Equipamentos Associados',
  Q1UA34: 'Construção e Engenharia',
  V1NO34: 'Fundos de Investimento Imobiliário (FIIs)',
  REGN34: 'Biotecnologia',
  TXRX3: 'Têxteis, Vestuário e Produtos de Luxo',
  RNEW11: 'Produtores de Eletricidade independentes e Energia Renovável',
  U1RI34: 'Empresas de Trading & Distribuidores',
  R1SG34: 'Serviços Comerciais & Suprimentos',
  W1YN34: 'Hotéis, Restaurantes e Lazer',
  RIOT34: 'Metais e Mineração',
  R1KU34: '',
  R1OL34: 'Serviços Comerciais & Suprimentos',
  R1OP34: 'Conglomerados Industriais',
  SAPR11: 'Captação, Tratamento e Distribuição de Água',
  SNSY3: 'Químicos',
  SLED4: 'Varejo Especializado',
  S1TX34: '',
  XPSF11: 'Mercados de Capitais',
  S1SL34: 'Semicondutores e Equipamentos Associados',
  S1NA34: 'Maquinário',
  S2NW34: '',
  S1PO34: 'Entretenimento',
  S1TT34: 'Mercados de Capitais',
  S1YK34: 'Equipamentos e Suprimentos Médicos',
  S1NP34: 'Software',
  S1YY34: 'Alimentos e Produtos Básicos de Consumo',
  TAEE11: 'Eléctricas',
  TAEE3: 'Eléctricas',
  I1RP34: 'Produtos de construção',
  T1EC34: 'Equipamentos e serviços de energia',
  U1BE34: 'Rodovia e Ferrovia',
  T1FX34: 'Equipamentos e Suprimentos Médicos',
  TLNC34: 'Serviços Diversificados de Telecomunicação',
  T1XT34: 'Espaço Aéreo e Defesa',
  T1MU34: 'Serviços de Telecomunicação Sem Fio',
  W1LT34: 'Seguro',
  T1DG34: 'Espaço Aéreo e Defesa',
  T1RI34: 'Mídia e Serviços Interativos',
  T1WL34: 'Serviços de TI',
  U1DR34: 'Fundos de Investimento Imobiliário (FIIs)',
  V1TA34: 'Fundos de Investimento Imobiliário (FIIs)',
  C1BS34: 'Mídia',
  VIVA3: 'Têxteis, Vestuário e Produtos de Luxo',
  W1EL34: 'Fundos de Investimento Imobiliário (FIIs)',
  MWET3: 'Componentes Automotivos',
  W1HR34: 'Bens domésticos duráveis',
  W1IX34: 'Serviços de TI',
  W1DA34: 'Software',
  W1PP34: '',
  X1LN34: 'Semicondutores e Equipamentos Associados',
  X1YL34: 'Maquinário',
  Z1TS34: 'Produtos farmacêutico'
}

export default {
  ticker2industry
}
