const ticker2sector = {
  FATN11: 'Financeiro',
  BITO39: '',
  HFOF11: 'Financeiro',
  KISU11: '',
  MMMC34: 'Industriais',
  RRRP3: 'Energia',
  FISC11: 'Imóveis',
  BIVB39: '',
  P1SX34: 'Energia',
  ESUT11: 'Financeiro',
  A1OS34: 'Industriais',
  GOGL34: 'Serviços de Comunicação',
  CEAB3: 'Produtos de Consumo Discricionário',
  EPAR3: 'Consumo Cíclico',
  GPIV33: 'Financeiro',
  BRGE5: 'Financeiro',
  ELET5: 'Utilidades',
  ESUD11: 'Financeiro',
  CEBR5: 'Utilidades',
  CSRN5: 'Utilidades',
  A1BB34: 'Industriais',
  ABTT34: 'Saúde',
  ABBV34: 'Saúde',
  ABCB4: 'Financeiro',
  A1BM34: 'Saúde',
  ACNB34: 'Tecnologia da Informação',
  EALT4: 'Materiais',
  EALT3: 'Materiais',
  ATVI34: 'Serviços de Comunicação',
  BACW39: 'Financeiro',
  CALI4: 'Industriais',
  BRGE3: 'Financeiro',
  BRGE8: 'Financeiro',
  BRGE6: 'Financeiro',
  BRGE11: 'Financeiro',
  BRGE12: 'Financeiro',
  ADBE34: 'Tecnologia da Informação',
  ADPR34: 'Tecnologia da Informação',
  A1AP34: 'Produtos de Consumo Discricionário',
  A1MD34: 'Tecnologia da Informação',
  AERI3: 'Industriais',
  TIET3: 'Utilidades',
  TIET4: 'Utilidades',
  AESB3: 'Utilidades',
  A1ES34: 'Utilidades',
  AFHI11: '',
  AFCR11: 'Financeiro',
  A1FL34: 'Financeiro',
  AFLT3: 'Utilidades',
  DBAG34: '',
  C1SU34: 'Financeiro',
  A1GI34: 'Saúde',
  SLCE3: 'Produtos de Consumo Básico',
  QAGR11: 'Financeiro',
  BTAL11: '',
  AGXY3: '',
  AIGB34: '',
  A1LK34: 'Industriais',
  S1EA34: 'Materiais',
  A1PD34: 'Materiais',
  DEAI34: 'Industriais',
  W1AB34: 'Industriais',
  AIRB34: 'Produtos de Consumo Discricionário',
  AALL34: 'Industriais',
  U1AL34: 'Industriais',
  S1OU34: 'Industriais',
  A1KA34: 'Tecnologia da Informação',
  RZAK11: 'Financeiro',
  A1LB34: 'Materiais',
  A1RE34: 'Imóveis',
  A1LX34: 'Saúde',
  RPAD5: 'Financeiro',
  RPAD3: 'Financeiro',
  BRIV4: 'Financeiro',
  CRIV4: 'Financeiro',
  BRIV3: 'Financeiro',
  CRIV3: 'Financeiro',
  RPAD6: 'Financeiro',
  CSAB4: 'Financeiro',
  PEAB3: 'Industriais',
  PEAB4: 'Industriais',
  CSAB3: 'Financeiro',
  ALSO3: 'Imóveis',
  ALZR11: 'Financeiro',
  BABA34: 'Produtos de Consumo Discricionário',
  A1LG34: 'Saúde',
  BAUH4: 'Produtos de Consumo Básico',
  A1GN34: 'Industriais',
  A1LL34: 'Tecnologia da Informação',
  A1EN34: 'Utilidades',
  AALR3: 'Saúde',
  ALLD3: 'Produtos de Consumo Discricionário',
  JPPA11: 'Financeiro',
  ALPK3: 'Industriais',
  A1TT34: 'Financeiro',
  ALMI11: '',
  ALPA3: 'Produtos de Consumo Discricionário',
  ALPA4: 'Produtos de Consumo Discricionário',
  APER3: 'Financeiro',
  RBRF11: 'Financeiro',
  GOGL35: 'Serviços de Comunicação',
  AVLL3: 'Produtos de Consumo Discricionário',
  RIOS3: '',
  MOOO34: 'Produtos de Consumo Básico',
  ALUP3: 'Utilidades',
  ALUP11: 'Utilidades',
  ALUP4: 'Utilidades',
  AMZO34: 'Produtos de Consumo Discricionário',
  BAZA3: 'Financeiro',
  ABEV3: 'Produtos de Consumo Básico',
  AMBP3: 'Serviços',
  A1EE34: 'Utilidades',
  M1AA34: 'Imóveis',
  SULA4: 'Financeiro',
  A1MX34: '',
  BOAC34: '',
  SULA3: 'Financeiro',
  SULA11: 'Financeiro',
  NOKI34: 'Tecnologia da Informação',
  A1EP34: 'Utilidades',
  T1OW34: 'Imóveis',
  B1TI34: 'Produtos de Consumo Básico',
  AXPB34: '',
  A1WK34: 'Utilidades',
  LAME4: 'Serviços',
  LAME3: 'Serviços',
  E1NI34: 'Utilidades',
  A1MP34: 'Financeiro',
  A1MB34: 'Saúde',
  A1ME34: 'Industriais',
  AMGN34: 'Saúde',
  A1PH34: 'Tecnologia da Informação',
  CBEE3: 'Utilidades',
  A1DI34: 'Tecnologia da Informação',
  V1RS34: 'Industriais',
  A1IV34: '',
  SPGI34: 'Financeiro',
  CARE11: 'Imóveis',
  B1DX34: 'Saúde',
  ATSA11: 'Financeiro',
  FAED11: 'Imóveis',
  PQAG11: 'Financeiro',
  ABUD34: 'Produtos de Consumo Básico',
  ANIM3: 'Serviços',
  ANIM3T: '',
  A1NS34: 'Tecnologia da Informação',
  A1NT34: 'Saúde',
  A1ON34: 'Financeiro',
  A1PA34: 'Energia',
  AAPL34: 'Tecnologia da Informação',
  A1MT34: 'Tecnologia da Informação',
  APTV34: 'Produtos de Consumo Discricionário',
  MOAR3: 'Financeiro',
  ARMT34: 'Materiais',
  A1DM34: 'Produtos de Consumo Básico',
  ARNC34: 'Industriais',
  ARCT11: 'Financeiro',
  ARZZ3: 'Consumo Cíclico',
  A1NE34: 'Tecnologia da Informação',
  TASA3: 'Industriais',
  TASA4: 'Industriais',
  TASA13: '',
  TASA17: '',
  TASA15: '',
  U1AI34: 'Produtos de Consumo Discricionário',
  A1JG34: 'Financeiro',
  EAIN34: 'Serviços de Comunicação',
  A1SN34: 'Saúde',
  N1VO34: 'Saúde',
  ASML34: 'Tecnologia da Informação',
  ASAI3: 'Consumo Não-Cíclico',
  J1KH34: 'Tecnologia da Informação',
  A1SU34: 'Financeiro',
  A1ZN34: 'Saúde',
  BCIA11: 'Imóveis',
  FIGS11: 'Imóveis',
  TGAR11: 'Financeiro',
  HSAF11: 'Financeiro',
  VSPT3: 'Industriais',
  ATMP3: 'Industriais',
  A1TM34: 'Utilidades',
  ATOM3: 'Serviços de Comunicação',
  ATTB34: 'Serviços de Comunicação',
  AURA33: 'Materiais',
  A1UT34: 'Tecnologia da Informação',
  R1OK34: 'Industriais',
  AIEC11: 'Financeiro',
  A1VB34: 'Imóveis',
  A1VY34: 'Materiais',
  AZEV3: 'Industriais',
  AZEV4: 'Industriais',
  AZUL4: 'Transporte',
  PCAR3: 'Serviços',
  EQPA6: 'Utilidades',
  J1BH34: 'Industriais',
  JBDU3: 'Materiais',
  BRKM6: 'Materiais Básicos',
  CPLE6: 'Utilidades',
  CEBR6: 'Utilidades',
  CSRN6: 'Utilidades',
  JBDU4: 'Materiais',
  BTOW3: 'Produtos de Consumo Discricionário',
  B3SA3: 'Financeiro',
  BAHI3: 'Financeiro',
  BIDU34: 'Serviços de Comunicação',
  B1KR34: 'Energia',
  B1LL34: 'Materiais',
  BBAS3: 'Financeiro',
  BMEB4: 'Financeiro',
  BIDI4: 'Financeiro',
  BPAC3: 'Financeiro',
  BIDI11: 'Financeiro',
  BGIP3: 'Financeiro',
  BMEB3: 'Financeiro',
  BMIN3: 'Financeiro',
  MODL11: '',
  BMGB4: 'Financeiro',
  BIDI3: 'Financeiro',
  BIDI4T: '',
  BPAC5: 'Financeiro',
  BSLI3: 'Financeiro',
  BPAN4: 'Financeiro',
  BCSA34: 'Financeiro',
  BMIN4: 'Financeiro',
  USBC34: 'Financeiro',
  FFTD34: 'Financeiro',
  Z1IO34: 'Financeiro',
  H1BA34: 'Financeiro',
  BGIP4: 'Financeiro',
  BCRI11: 'Financeiro',
  BEES3: 'Financeiro',
  BEES4: 'Financeiro',
  BONY34: '',
  F1RC34: 'Financeiro',
  M1TB34: 'Financeiro',
  MSBR34: '',
  H1DB34: 'Financeiro',
  I1BN34: 'Financeiro',
  L1YG34: 'Financeiro',
  BRSR5: 'Financeiro',
  BRSR6: 'Financeiro',
  BRSR3: 'Financeiro',
  BNFS11: 'Financeiro',
  B1CS34: '',
  BDLL4: 'Industriais',
  BARI11: 'Financeiro',
  BALM3: 'Saúde',
  BALM4: 'Saúde',
  B1AX34: 'Saúde',
  BBRC11: 'Imóveis',
  RDPD11: 'Financeiro',
  RNDP11: 'Financeiro',
  BBFO11: 'Financeiro',
  BBSE3: 'Financeiro',
  BBIM11: 'Financeiro',
  BBPO11: 'Imóveis',
  BILB34: '',
  BEWJ39: '',
  BOEI34: 'Industriais',
  CHVX34: 'Energia',
  IBMB34: 'Tecnologia da Informação',
  UPSS34: 'Industriais',
  DHER34: 'Saúde',
  KMBB34: 'Produtos de Consumo Básico',
  XRXB34: 'Tecnologia da Informação',
  DUKB34: 'Utilidades',
  UPAC34: 'Industriais',
  FDMO34: 'Produtos de Consumo Discricionário',
  ITLC34: 'Tecnologia da Informação',
  JNJB34: 'Saúde',
  MSCD34: 'Tecnologia da Informação',
  NIKE34: 'Produtos de Consumo Discricionário',
  KHCB34: 'Produtos de Consumo Básico',
  COWC34: 'Produtos de Consumo Básico',
  GPSI34: 'Produtos de Consumo Discricionário',
  MACY34: 'Produtos de Consumo Discricionário',
  ROST34: 'Produtos de Consumo Discricionário',
  DTCY3: 'Industriais',
  R1MD34: 'Saúde',
  FMXB34: 'Produtos de Consumo Básico',
  M1TD34: 'Saúde',
  SIMN34: 'Imóveis',
  RDSA35: 'Energia',
  W1MG34: 'Serviços de Comunicação',
  Z1OM34: 'Tecnologia da Informação',
  N1VS34: 'Saúde',
  SAPP34: 'Tecnologia da Informação',
  WGBA34: 'Produtos de Consumo Básico',
  TGTB34: 'Produtos de Consumo Discricionário',
  BOXP34: 'Imóveis',
  GPRO34: 'Produtos de Consumo Discricionário',
  LBRN34: 'Produtos de Consumo Discricionário',
  TWTR34: 'Serviços de Comunicação',
  SLBG34: 'Energia',
  BBYY34: 'Produtos de Consumo Discricionário',
  LMTB34: 'Industriais',
  MSFT34: '',
  PFIZ34: 'Saúde',
  SBUB34: 'Produtos de Consumo Discricionário',
  GDBR34: 'Industriais',
  HSHY34: 'Produtos de Consumo Básico',
  E1WL34: 'Saúde',
  TSMC34: 'Tecnologia da Informação',
  CATP34: 'Industriais',
  DISB34: 'Serviços de Comunicação',
  EXXO34: 'Energia',
  HALI34: 'Energia',
  HPQB34: 'Tecnologia da Informação',
  ORCL34: 'Tecnologia da Informação',
  WFCO34: 'Financeiro',
  WUNI34: 'Tecnologia da Informação',
  LILY34: 'Saúde',
  NFLX34: 'Serviços de Comunicação',
  BLAK34: 'Financeiro',
  CVSH34: 'Saúde',
  GILD34: 'Saúde',
  SCHW34: 'Financeiro',
  W1BO34: 'Serviços de Comunicação',
  CTGP34: '',
  GEOO34: 'Industriais',
  GSGI34: 'Financeiro',
  HOME34: 'Produtos de Consumo Discricionário',
  JPMC34: '',
  WALM34: 'Produtos de Consumo Básico',
  BIIB34: 'Saúde',
  CTSH34: 'Tecnologia da Informação',
  SSFO34: 'Tecnologia da Informação',
  COLG34: 'Produtos de Consumo Básico',
  COTY34: 'Produtos de Consumo Básico',
  EBAY34: 'Produtos de Consumo Discricionário',
  MDLZ34: 'Produtos de Consumo Básico',
  MOSC34: 'Materiais',
  RYTT34: 'Industriais',
  PAGS34: '',
  UBSG34: 'Financeiro',
  TSLA34: 'Produtos de Consumo Discricionário',
  MELI34: 'Produtos de Consumo Discricionário',
  M1SC34: 'Financeiro',
  METB34: 'Financeiro',
  BMYB34: 'Saúde',
  FCXO34: 'Materiais',
  FDXB34: 'Industriais',
  QCOM34: 'Tecnologia da Informação',
  TEXA34: 'Tecnologia da Informação',
  COPH34: 'Energia',
  FBOK34: 'Serviços de Comunicação',
  MCDC34: 'Produtos de Consumo Discricionário',
  PEPB34: 'Produtos de Consumo Básico',
  BERK34: 'Financeiro',
  CMCS34: 'Serviços de Comunicação',
  COCA34: 'Produtos de Consumo Básico',
  CSCO34: 'Tecnologia da Informação',
  MRCK34: 'Saúde',
  PGCO34: 'Produtos de Consumo Básico',
  VERZ34: 'Serviços de Comunicação',
  VISA34: '',
  HONB34: '',
  DDNB34: 'Materiais',
  GMCO34: 'Produtos de Consumo Discricionário',
  FSLR34: '',
  MDTC34: 'Saúde',
  RIGG34: 'Energia',
  TRVC34: 'Financeiro',
  USSX34: 'Materiais',
  VLOE34: 'Energia',
  B1IL34: 'Serviços de Comunicação',
  B1PP34: 'Energia',
  N1OW34: 'Tecnologia da Informação',
  UNHH34: 'Saúde',
  R1IN34: 'Imóveis',
  RDSA34: 'Energia',
  SNEC34: 'Produtos de Consumo Discricionário',
  ULEV34: 'Produtos de Consumo Básico',
  U1LT34: 'Produtos de Consumo Discricionário',
  B1GN34: 'Saúde',
  BMOB3: 'Tecnologia',
  M1NS34: 'Produtos de Consumo Básico',
  M1CB34: 'Produtos de Consumo Básico',
  B2YN34: 'Produtos de Consumo Básico',
  BHPG34: 'Materiais',
  BMKS3: 'Produtos de Consumo Discricionário',
  VITT3: '',
  B1MR34: 'Saúde',
  Z1BH34: 'Saúde',
  BIOM11: 'Saúde',
  BIOM3: 'Saúde',
  B1NT34: 'Saúde',
  BSEV3: 'Consumo Não-Cíclico',
  T1CH34: 'Saúde',
  S1WK34: 'Industriais',
  LLIS3: 'Produtos de Consumo Discricionário',
  BLAU3: 'Saúde',
  H1RB34: 'Produtos de Consumo Discricionário',
  BLCP11: 'Financeiro',
  BLMO11: 'Financeiro',
  BLMG11: 'Financeiro',
  BLMR11: 'Financeiro',
  BNBR3: 'Financeiro',
  RBBV11: 'Imóveis',
  SOJA3: 'Consumo Não-Cíclico',
  BOAS3: 'Industriais',
  BOBR4: 'Produtos de Consumo Básico',
  BKNG34: 'Produtos de Consumo Discricionário',
  B1WA34: 'Produtos de Consumo Discricionário',
  B1SX34: 'Saúde',
  BBRK3: 'Serviços',
  RECT11: 'Financeiro',
  BRML3: 'Imóveis',
  BRPR3: 'Imóveis',
  MBRF11: 'Imóveis',
  BRBI11: '',
  BBDC3: 'Financeiro',
  BBDC4: 'Financeiro',
  BRAP4: 'Materiais',
  BRAP3: 'Materiais',
  FPAB11: 'Imóveis',
  MDIA3: 'Produtos de Consumo Básico',
  CBOP11: 'Financeiro',
  C1AG34: 'Produtos de Consumo Básico',
  N1WL34: 'Produtos de Consumo Discricionário',
  F1BH34: 'Industriais',
  CVCB3: 'Produtos de Consumo Discricionário',
  HGBS11: 'Imóveis',
  IRBR3: 'Financeiro',
  BPFF11: 'Imóveis',
  SANB4: 'Financeiro',
  SANB3: 'Financeiro',
  ENBR3: 'Utilidades',
  LPSB3: 'Imóveis',
  FIIB11: 'Financeiro',
  MALL11: 'Financeiro',
  NCHB11: 'Financeiro',
  GSFI11: 'Financeiro',
  HBSA3: 'Industriais',
  OSXB3: 'Energia',
  SANB11: 'Financeiro',
  EGIE3: 'Utilidades',
  VIVT3: 'Serviços de Comunicação',
  STBP3: 'Industriais',
  MERC4: 'Financeiro',
  AGRO3: 'Produtos de Consumo Básico',
  BRKM3: 'Materiais Básicos',
  BRKM5: 'Materiais Básicos',
  RBED11: 'Imóveis',
  RBIV11: 'Financeiro',
  RBRS11: 'Financeiro',
  RBVO11: 'Financeiro',
  SDIL11: 'Imóveis',
  RBVA11: 'Imóveis',
  RBFF11: 'Imóveis',
  RCRB11: 'Imóveis',
  CRFF11: 'Financeiro',
  CXRI11: 'Financeiro',
  BZLI11: 'Financeiro',
  BSLI4: 'Financeiro',
  BREV11: 'Financeiro',
  IBFF11: 'Financeiro',
  BRCO11: 'Financeiro',
  BRFS3: 'Produtos de Consumo Básico',
  ESTR4: 'Produtos de Consumo Discricionário',
  BRIM11: 'Financeiro',
  BPRP11: 'Financeiro',
  AVGO34: 'Tecnologia da Informação',
  B1RF34: 'Tecnologia da Informação',
  B1FC34: 'Produtos de Consumo Básico',
  BRZP11: 'Financeiro',
  BTLG11: 'Imóveis',
  BPML11: 'Financeiro',
  FEXC11: '',
  BRCR11: 'Imóveis',
  BTCR11: 'Financeiro',
  BDIV11: 'Financeiro',
  BPAC11: 'Financeiro',
  BCFF11: '',
  BKBR3: 'Produtos de Consumo Discricionário',
  CEGR3: 'Utilidades',
  C1OG34: 'Energia',
  CEDO3: 'Produtos de Consumo Discricionário',
  C1DN34: 'Tecnologia da Informação',
  CXSE3: 'Financeiro',
  CXTL11: 'Imóveis',
  CXCO11: '',
  HCAR3: '',
  CAMB3: 'Produtos de Consumo Discricionário',
  CAML3: 'Produtos de Consumo Básico',
  C1PB34: 'Produtos de Consumo Básico',
  FCFL11: '',
  CNIC34: 'Industriais',
  CAJI34: 'Tecnologia da Informação',
  RBIR11: 'Financeiro',
  P1NW34: 'Utilidades',
  RBGS11: 'Imóveis',
  RBCO11: 'Financeiro',
  RRCI11: '',
  RBRD11: 'Imóveis',
  MCCI11: 'Financeiro',
  RBDS11: 'Financeiro',
  RFOF11: 'Financeiro',
  CAON34: 'Financeiro',
  CPFF11: 'Financeiro',
  CPTS11: 'Financeiro',
  HUSC11: 'Financeiro',
  CAPH34: 'Produtos de Consumo Discricionário',
  C1AH34: 'Saúde',
  CARD3: 'Tecnologia da Informação',
  R1CL34: 'Produtos de Consumo Discricionário',
  SCAR3: 'Imóveis',
  K1MX34: 'Produtos de Consumo Discricionário',
  C1CL34: 'Produtos de Consumo Discricionário',
  CRFB3: 'Produtos de Consumo Básico',
  CASN3: 'Utilidades',
  CASN4: 'Utilidades',
  C1CI34: 'Imóveis',
  CLSC3: 'Utilidades',
  C1BO34: 'Financeiro',
  C1BR34: 'Imóveis',
  CCPR3: 'Imóveis',
  CCRO3: 'Industriais',
  SADI11: 'Financeiro',
  HCTR11: 'Financeiro',
  CEBR3: 'Utilidades',
  CEDO4: 'Produtos de Consumo Discricionário',
  CEED3: 'Utilidades',
  EEEL3: 'Utilidades',
  CEED4: 'Utilidades',
  C1NS34: 'Materiais',
  CLSC4: 'Utilidades',
  GPAR3: 'Utilidades',
  CEPE5: 'Utilidades',
  RANI3: 'Materiais',
  MAPT3: 'Financeiro',
  MAPT4: 'Financeiro',
  CMIG4: 'Utilidades',
  CMIG3: 'Utilidades',
  CNES11: 'Financeiro',
  SBFG3: 'Serviços',
  C1NC34: 'Saúde',
  PQDP11: 'Financeiro',
  C1NP34: 'Utilidades',
  R1EG34: 'Imóveis',
  VISC11: 'Financeiro',
  CTXT11: 'Imóveis',
  L1MN34: 'Serviços de Comunicação',
  C1ER34: 'Saúde',
  CESP3: 'Utilidades',
  CESP5: 'Utilidades',
  CESP6: 'Utilidades',
  C1FI34: 'Materiais',
  C1HR34: 'Industriais',
  CHCM34: 'Serviços de Comunicação',
  C1HK34: 'Tecnologia da Informação',
  C1HI34: 'Energia',
  E1MN34: 'Materiais',
  BCHI39: '',
  C1HL34: 'Serviços de Comunicação',
  C1MG34: 'Produtos de Consumo Discricionário',
  C1BL34: 'Financeiro',
  FSTU11: '',
  FSRF11: '',
  FNAM11: 'Financeiro',
  HGTX3: 'Produtos de Consumo Discricionário',
  CIEL3: 'Financeiro',
  C1IC34: 'Saúde',
  C1TA34: 'Industriais',
  C1FG34: 'Financeiro',
  C1TX34: 'Tecnologia da Informação',
  K1CS34: 'Industriais',
  JFLL11: 'Financeiro',
  VVEO3: '',
  CHME34: 'Financeiro',
  C1MS34: 'Utilidades',
  C1EO34: '',
  HOND34: 'Produtos de Consumo Discricionário',
  H1PE34: 'Tecnologia da Informação',
  S1JM34: 'Produtos de Consumo Básico',
  PTCH34: '',
  W1YC34: 'Imóveis',
  TAKP34: 'Saúde',
  D1XC34: 'Tecnologia da Informação',
  I1PC34: 'Materiais',
  T1SO34: 'Utilidades',
  E1MR34: 'Industriais',
  V1MC34: 'Materiais',
  DEEC34: 'Industriais',
  T1SC34: 'Produtos de Consumo Discricionário',
  G1PC34: 'Produtos de Consumo Discricionário',
  K1RC34: 'Produtos de Consumo Básico',
  W1RK34: 'Materiais',
  S1HW34: 'Materiais',
  CEEB3: 'Utilidades',
  CEEB5: 'Utilidades',
  COCE5: 'Utilidades',
  COCE3: 'Utilidades',
  COGN3: 'Serviços',
  RCFF11: 'Financeiro',
  WLMM3: 'Industriais',
  WLMM4: 'Industriais',
  HAGA3: 'Industriais',
  C1MA34: 'Financeiro',
  CGAS5: 'Utilidades',
  CGAS3: 'Utilidades',
  CEOC11: 'Financeiro',
  S1BA34: 'Imóveis',
  CPLE11: 'Utilidades',
  MSPA3: 'Serviços de Comunicação',
  CPLE5: 'Utilidades',
  W1MB34: 'Energia',
  M1MC34: '',
  C1OO34: 'Saúde',
  ELCI34: 'Produtos de Consumo Básico',
  LOWC34: 'Produtos de Consumo Discricionário',
  I1PH34: 'Serviços de Comunicação',
  P1RG34: 'Saúde',
  T1EL34: 'Tecnologia da Informação',
  FCCQ11: 'Financeiro',
  E1DI34: 'Utilidades',
  CURY3: 'Bens de Capital',
  FLMA11: 'Financeiro',
  J1CI34: 'Industriais',
  C1PR34: 'Industriais',
  CSMG3: 'Utilidades',
  CPLE3: 'Utilidades',
  PICE11: 'Financeiro',
  G1LW34: 'Tecnologia da Informação',
  THRA11: '',
  VLOL11: 'Imóveis',
  XPCM11: 'Imóveis',
  PATC11: 'Financeiro',
  XTED11: 'Imóveis',
  CORR4: 'Imóveis',
  RLOG3: 'Transporte',
  CSAN3: 'Energia',
  CSRN3: 'Utilidades',
  CTNM4: 'Produtos de Consumo Discricionário',
  CTNM3: 'Produtos de Consumo Discricionário',
  GGRC11: 'Financeiro',
  LOGG3: 'Imóveis',
  CPFE3: 'Utilidades',
  CRDE3: 'Imóveis',
  QAMI11: '',
  IFRA11: 'Financeiro',
  HGIC11: 'Financeiro',
  CRHP34: 'Materiais',
  CVBI11: 'Financeiro',
  KNHY11: 'Financeiro',
  VGIP11: 'Financeiro',
  HCRI11: '',
  CRPG3: 'Materiais',
  CRPG5: 'Materiais',
  CRPG6: 'Materiais',
  N1CL34: 'Produtos de Consumo Discricionário',
  CSED3: 'Produtos de Consumo Discricionário',
  XPCI11: 'Financeiro',
  RBRY11: 'Financeiro',
  HGRE11: 'Imóveis',
  HGCR11: 'Financeiro',
  HGPO11: 'Financeiro',
  HGLG11: 'Imóveis',
  HGFF11: 'Financeiro',
  HGRU11: 'Financeiro',
  CMIN3: 'Materiais',
  CSNA3: 'Materiais',
  CSXC34: 'Industriais',
  TRPL4: 'Utilidades',
  TRPL3: 'Utilidades',
  C1MI34: 'Industriais',
  CVCB3T: '',
  IFCM3: '',
  CYRE3: 'Produtos de Consumo Discricionário',
  IFID11: 'Financeiro',
  RDOR3: 'Saúde',
  D1HI34: 'Produtos de Consumo Discricionário',
  DMVF3: 'Produtos de Consumo Básico',
  HMOC11: '',
  D1RI34: 'Produtos de Consumo Discricionário',
  DASA3: 'Saúde',
  H1OG34: 'Produtos de Consumo Discricionário',
  EQPA3: 'Utilidades',
  EQPA5: 'Utilidades',
  OUFF11: 'Financeiro',
  KNIP11: 'Financeiro',
  KDIF11: 'Financeiro',
  HREC11: 'Financeiro',
  RECX11: 'Financeiro',
  MGFF11: 'Financeiro',
  FNOR11: 'Financeiro',
  SNFF11: '',
  GCFF11: 'Financeiro',
  NSLU11: 'Financeiro',
  PLOG11: 'Financeiro',
  MATD3: 'Saúde',
  D1EL34: 'Tecnologia da Informação',
  HCST11: 'Financeiro',
  MFII11: 'Imóveis',
  MFAI11: 'Financeiro',
  ORPD11: 'Financeiro',
  T2TD34: '',
  DEVA11: 'Financeiro',
  HRDF11: 'Financeiro',
  D1VN34: '',
  DEXP3: 'Materiais Básicos',
  DEXP4: 'Materiais Básicos',
  DEOP34: 'Produtos de Consumo Básico',
  Q1UE34: 'Saúde',
  F1AN34: 'Energia',
  D1LR34: 'Imóveis',
  W1DC34: 'Tecnologia da Informação',
  PNVL3: 'Produtos de Consumo Básico',
  PNVL4: 'Produtos de Consumo Básico',
  DIRR3: 'Produtos de Consumo Discricionário',
  D1FS34: 'Financeiro',
  DCVY35: 'Serviços de Comunicação',
  D1IS34: 'Serviços de Comunicação',
  BRDT3: 'Produtos de Consumo Discricionário',
  EQPA7: 'Utilidades',
  BIYW39: '',
  D1OC34: 'Tecnologia da Informação',
  DOHL3: 'Produtos de Consumo Discricionário',
  DOHL4: 'Produtos de Consumo Discricionário',
  DGCO34: 'Produtos de Consumo Discricionário',
  HPDP11: 'Financeiro',
  FISD11: 'Financeiro',
  D1OM34: 'Utilidades',
  DMMO11: '',
  DMMO3: 'Energia',
  DMMO3T: '',
  DOTZ3: '',
  D1OV34: 'Industriais',
  SPTW11: 'Imóveis',
  WSON33: 'Industriais',
  RADL3: 'Produtos de Consumo Básico',
  D1TE34: 'Utilidades',
  MDNE3: 'Imóveis',
  D1RE34: 'Imóveis',
  DTEX3: 'Bens de Capital',
  IFIE11: 'Financeiro',
  GGPS3: 'Industriais',
  E1TN34: 'Industriais',
  E1CL34: 'Materiais',
  E1CO34: 'Energia',
  ECOR3: 'Industriais',
  EDGA11: 'Imóveis',
  E1IX34: 'Utilidades',
  SEER3: 'Produtos de Consumo Discricionário',
  SEER3T: '',
  TORD11: 'Financeiro',
  EKTR4: 'Utilidades',
  EKTR3: 'Utilidades',
  ELET6: 'Utilidades',
  ELET3: 'Utilidades',
  LIPR3: 'Utilidades',
  ELMD3: 'Serviços de Comunicação',
  EMAE4: 'Utilidades',
  EMBR3: 'Industriais',
  ENAT3: 'Energia',
  ECPR3: 'Produtos de Consumo Discricionário',
  VIGT11: 'Financeiro',
  REDE3: 'Utilidades',
  GEPA3: 'Utilidades',
  GEPA4: 'Utilidades',
  POWE3: 'Utilidades',
  ENMT4: 'Utilidades',
  ENGI4: 'Utilidades',
  ENGI11: 'Utilidades',
  ENGI3: 'Utilidades',
  ENMT3: 'Utilidades',
  NEXT34: 'Utilidades',
  X1EL34: 'Utilidades',
  S1RE34: 'Utilidades',
  W1EC34: 'Utilidades',
  N1RG34: 'Utilidades',
  ENEV3: 'Utilidades',
  J1EG34: 'Industriais',
  ENJU3: 'Produtos de Consumo Discricionário',
  E1TR34: 'Utilidades',
  P1EG34: 'Utilidades',
  E1OG34: 'Energia',
  EQTL3: 'Utilidades',
  E1FX34: 'Industriais',
  EQIX34: 'Imóveis',
  KNRE11: 'Imóveis',
  E1QR34: 'Imóveis',
  E1RI34: 'Tecnologia da Informação',
  ESPA3: 'Produtos de Consumo Discricionário',
  E1SS34: 'Imóveis',
  EEEL4: 'Utilidades',
  MORE11: 'Financeiro',
  JSRE11: 'Imóveis',
  TRXB11: 'Financeiro',
  OURE11: 'Financeiro',
  ETER3: 'Materiais',
  BEZU39: '',
  EUCA4: 'Materiais',
  EUCA3: 'Materiais',
  EURO11: 'Financeiro',
  KEVE11: 'Financeiro',
  KINP11: 'Financeiro',
  EVEN3: 'Bens de Capital',
  E1VE34: 'Financeiro',
  E1VR34: 'Utilidades',
  E1SE34: 'Utilidades',
  I1CE34: 'Financeiro',
  E1XC34: 'Utilidades',
  EXGR34: 'Produtos de Consumo Discricionário',
  E1XP34: 'Industriais',
  E1XR34: 'Imóveis',
  EZTC3: 'Produtos de Consumo Discricionário',
  F1FI34: 'Tecnologia da Informação',
  VRTA11: 'Financeiro',
  F1RI34: 'Imóveis',
  FHER3: 'Materiais',
  FESA4: 'Materiais',
  FESA3: 'Materiais',
  SFND11: 'Imóveis',
  F1NI34: 'Tecnologia da Informação',
  TFCO4: 'Produtos de Consumo Discricionário',
  G1FI34: 'Materiais',
  KNCR11: 'Financeiro',
  NEWU11: 'Imóveis',
  SHPH11: 'Financeiro',
  SCPF11: 'Financeiro',
  HTMX11: 'Financeiro',
  XPLG11: 'Financeiro',
  LVBI11: '',
  VTLT11: 'Financeiro',
  DMAC11: 'Financeiro',
  VINO11: 'Financeiro',
  HLOG11: 'Financeiro',
  FPNG11: 'Financeiro',
  RCFA11: '',
  MGHT11: 'Financeiro',
  LASC11: 'Financeiro',
  VSEC11: 'Financeiro',
  URPR11: 'Financeiro',
  MGCR11: 'Financeiro',
  RELG11: 'Financeiro',
  OUJP11: 'Financeiro',
  VGIR11: 'Financeiro',
  VILG11: 'Financeiro',
  XPIN11: 'Financeiro',
  FIVN11: 'Financeiro',
  FLRP11: '',
  MAXR11: 'Financeiro',
  TRNT11: '',
  ONEF11: 'Financeiro',
  RNGO11: 'Imóveis',
  LGCP11: 'Financeiro',
  VVPR11: '',
  HABT11: 'Financeiro',
  NPAR11: 'Financeiro',
  RBRP11: 'Financeiro',
  REIT11: 'Financeiro',
  SPAF11: 'Financeiro',
  ARRI11: 'Financeiro',
  RBRL11: 'Financeiro',
  HOSI11: 'Financeiro',
  SEQR11: 'Financeiro',
  ABCP11: 'Financeiro',
  KNRI11: 'Imóveis',
  FMOF11: 'Financeiro',
  PLRI11: 'Financeiro',
  JRDM11: 'Imóveis',
  VSHO11: 'Imóveis',
  KFOF11: 'Financeiro',
  GTWR11: 'Financeiro',
  FVPQ11: 'Financeiro',
  HBRH11: 'Financeiro',
  GALG11: 'Financeiro',
  WPLZ11: 'Financeiro',
  HSML11: 'Financeiro',
  TORM13: 'Financeiro',
  LUGG11: 'Financeiro',
  SARE11: 'Financeiro',
  VIUR11: '',
  MXRF11: 'Financeiro',
  PRSV11: 'Imóveis',
  VGHF11: 'Financeiro',
  RMAI11: '',
  HSLG11: 'Financeiro',
  PORD11: 'Imóveis',
  XPML11: '',
  RBRR11: 'Financeiro',
  TOUR11: 'Financeiro',
  XPPR11: 'Financeiro',
  VOTS11: 'Financeiro',
  BICR11: 'Financeiro',
  RZTR11: 'Financeiro',
  RECR11: 'Financeiro',
  IRDM11: 'Financeiro',
  FSPE11: 'Financeiro',
  PABY11: 'Imóveis',
  KNSC11: 'Financeiro',
  TRXF11: 'Financeiro',
  RVBI11: 'Financeiro',
  QIFF11: 'Financeiro',
  LFTT11: 'Financeiro',
  J1EF34: '',
  P1FG34: 'Financeiro',
  R1FC34: 'Financeiro',
  R1JF34: 'Financeiro',
  H1IG34: 'Financeiro',
  M1UF34: 'Financeiro',
  PNCS34: 'Financeiro',
  S1IV34: 'Financeiro',
  B1BT34: 'Financeiro',
  S1YF34: 'Financeiro',
  P1BC34: 'Financeiro',
  OFSA3: 'Saúde',
  XPOM11: '',
  XPIE11: 'Financeiro',
  PFIN11: 'Financeiro',
  F1EC34: 'Utilidades',
  F1IS34: 'Tecnologia da Informação',
  TMOS34: 'Saúde',
  I1FF34: 'Materiais',
  FLTC34: 'Tecnologia da Informação',
  FLRY3: 'Saúde',
  F1LI34: '',
  F1LS34: 'Industriais',
  F1MC34: 'Materiais',
  H1RL34: 'Produtos de Consumo Básico',
  SHOW3: 'Serviços',
  JFEN3: 'Imóveis',
  F1TN34: 'Tecnologia da Informação',
  F1TV34: 'Industriais',
  FOXC34: 'Serviços de Comunicação',
  F1RA34: 'Financeiro',
  FRAS3: 'Produtos de Consumo Discricionário',
  HUSI11: 'Financeiro',
  G2DI33: '',
  GFSA3: 'Produtos de Consumo Discricionário',
  G1RM34: 'Produtos de Consumo Discricionário',
  G1AR34: 'Tecnologia da Informação',
  G1DS34: 'Tecnologia da Informação',
  G1MI34: 'Produtos de Consumo Básico',
  GSHP3: 'Serviços',
  GPRK34: 'Energia',
  OMGE3: 'Utilidades',
  GGBR4: 'Materiais Básicos',
  GGBR3: 'Materiais Básicos',
  GOAU3: 'Materiais',
  GOAU4: 'Materiais',
  NINJ3: '',
  G1SK34: 'Saúde',
  L1BT34: 'Serviços de Comunicação',
  G1PI34: 'Tecnologia da Informação',
  G1LL34: 'Financeiro',
  GOLL11: 'Industriais',
  GOLL12: 'Industriais',
  GOLL4: 'Industriais',
  BIAU39: '',
  G1WW34: 'Industriais',
  CGRA3: 'Produtos de Consumo Discricionário',
  CGRA4: 'Produtos de Consumo Discricionário',
  S1LG34: 'Imóveis',
  GRND3: 'Produtos de Consumo Discricionário',
  INGG34: 'Financeiro',
  T1RO34: 'Financeiro',
  U1NM34: 'Financeiro',
  CRIP34: 'Produtos de Consumo Discricionário',
  O1MC34: 'Serviços de Comunicação',
  H1TH34: 'Produtos de Consumo Discricionário',
  V1OD34: 'Serviços de Comunicação',
  NOCG34: 'Industriais',
  SOMA3: 'Produtos de Consumo Discricionário',
  GMAT3: 'Produtos de Consumo Básico',
  GUAR3: 'Produtos de Consumo Discricionário',
  HBTS5: 'Industriais',
  HAGA4: 'Industriais',
  R1HI34: 'Industriais',
  H1BI34: 'Produtos de Consumo Discricionário',
  HAPV3: 'Saúde',
  H1AS34: 'Produtos de Consumo Discricionário',
  HBRE3: 'Imóveis',
  H1CA34: 'Saúde',
  U1HS34: 'Saúde',
  P1EA34: 'Imóveis',
  HBOR3: 'Imóveis',
  H1SI34: 'Saúde',
  HETA4: 'Produtos de Consumo Discricionário',
  PARD3: 'Saúde',
  H1ES34: 'Energia',
  H1LT34: 'Produtos de Consumo Discricionário',
  R1YA34: 'Industriais',
  H1SB34: 'Financeiro',
  I1QV34: 'Saúde',
  N1LS34: 'Industriais',
  NMRH34: 'Financeiro',
  PYPL34: 'Tecnologia da Informação',
  M1KT34: 'Financeiro',
  V1IP34: 'Produtos de Consumo Discricionário',
  L1WH34: 'Produtos de Consumo Básico',
  H1FC34: 'Energia',
  H1OL34: 'Saúde',
  H1ST34: 'Imóveis',
  HOOT4: 'Produtos de Consumo Discricionário',
  H1UM34: 'Saúde',
  H1II34: 'Industriais',
  HYPE3: 'Saúde',
  I1DX34: 'Saúde',
  IGBR3: 'Imóveis',
  MTIG4: 'Materiais',
  IGTA3: 'Imóveis',
  I1NF34: 'Industriais',
  I1TW34: 'Industriais',
  I1LM34: 'Saúde',
  MEAL3: 'Produtos de Consumo Discricionário',
  VSLH11: 'Financeiro',
  LOGN3: 'Industriais',
  I1NC34: 'Saúde',
  ROMI3: 'Industriais',
  PRNR3: 'Industriais',
  L1YB34: 'Materiais',
  M1HK34: 'Produtos de Consumo Discricionário',
  P1PG34: 'Materiais',
  INEP4: 'Industriais',
  INEP3: 'Industriais',
  POSI3: 'Tecnologia da Informação',
  GENT3: '',
  I1FO34: '',
  M1XI34: 'Tecnologia da Informação',
  INTB3: 'Tecnologia da Informação',
  T1TW34: 'Serviços de Comunicação',
  GNDI3: 'Saúde',
  M1GM34: 'Produtos de Consumo Discricionário',
  PHMO34: 'Produtos de Consumo Básico',
  INTU34: 'Tecnologia da Informação',
  I1SR34: 'Saúde',
  I1VZ34: 'Financeiro',
  LUXM4: 'Industriais',
  MYPK3: 'Industriais',
  I1PG34: 'Tecnologia da Informação',
  I1RM34: 'Imóveis',
  BSLV39: 'Financeiro',
  ITUB3: 'Financeiro',
  ITUB4: 'Financeiro',
  ITSA4: 'Financeiro',
  ITSA3: 'Financeiro',
  JALL3: 'Produtos de Consumo Básico',
  JBSS3: 'Consumo Não-Cíclico',
  JDCO34: 'Produtos de Consumo Discricionário',
  JPSA3: 'Imóveis',
  JHSF3: 'Imóveis',
  JOPA4: 'Produtos de Consumo Básico',
  JOPA3: 'Produtos de Consumo Básico',
  JSLG3: 'Industriais',
  J1NP34: 'Tecnologia da Informação',
  VCJR11: 'Financeiro',
  CTKA4: 'Produtos de Consumo Discricionário',
  CTKA3: 'Produtos de Consumo Discricionário',
  K1EL34: 'Produtos de Consumo Básico',
  KEPL3: 'Industriais',
  KEPL11: 'Industriais',
  K1EY34: 'Financeiro',
  K1SG34: 'Tecnologia da Informação',
  K1IM34: 'Imóveis',
  KMIC34: 'Energia',
  K1LA34: 'Tecnologia da Informação',
  KLBN4: 'Materiais Básicos',
  KLBN11: 'Materiais Básicos',
  KLBN3: 'Materiais Básicos',
  K1SS34: 'Produtos de Consumo Discricionário',
  PHGN34: 'Saúde',
  KRSA3: '',
  L1HX34: 'Industriais',
  L1CA34: 'Saúde',
  L1RC34: 'Tecnologia da Informação',
  R1LC34: 'Produtos de Consumo Discricionário',
  LAVV3: 'Imóveis',
  L1EG34: 'Produtos de Consumo Discricionário',
  L1EN34: 'Produtos de Consumo Discricionário',
  LEVE3: 'Produtos de Consumo Discricionário',
  LSXM35: 'Serviços de Comunicação',
  LSXM34: '',
  LMED3: 'Saúde',
  LIGT3: 'Utilidades',
  L1NC34: 'Financeiro',
  L1IN34: 'Materiais',
  LINX3: 'Tecnologia',
  L1KQ34: 'Produtos de Consumo Discricionário',
  RENT3: 'Industriais',
  LCAM3: 'Industriais',
  LWSA3: 'Tecnologia da Informação',
  L1OE34: 'Financeiro',
  OULG11: 'Imóveis',
  LREN3: 'Produtos de Consumo Discricionário',
  AMAR3: 'Produtos de Consumo Discricionário',
  LJQQ3: 'Produtos de Consumo Discricionário',
  MGLU3: 'Produtos de Consumo Discricionário',
  L1UL34: 'Produtos de Consumo Discricionário',
  LUPA3: 'Energia',
  W1MC34: 'Industriais',
  MGEL4: 'Produtos de Consumo Discricionário',
  RPMG3: 'Energia',
  M1RO34: 'Energia',
  M1PC34: 'Energia',
  POMO4: 'Industriais',
  POMO3: 'Industriais',
  MRFG3: 'Produtos de Consumo Básico',
  M1LM34: 'Materiais',
  MKLC34: 'Financeiro',
  M1TT34: 'Produtos de Consumo Discricionário',
  SMTO3: 'Consumo Não-Cíclico',
  M1AS34: 'Industriais',
  M1KC34: 'Produtos de Consumo Básico',
  M1CK34: 'Saúde',
  BDLL3: 'Industriais',
  V1AR34: '',
  MSPA4: 'Serviços de Comunicação',
  MELK3: 'Imóveis',
  PGMN3: 'Produtos de Consumo Básico',
  FRIO3: 'Industriais',
  MTSA3: 'Industriais',
  NORD3: 'Industriais',
  RSUL4: 'Industriais',
  MTSA4: 'Industriais',
  M1CH34: 'Tecnologia da Informação',
  MUTC34: 'Tecnologia da Informação',
  MILS3: 'Industriais',
  BEEF3: 'Produtos de Consumo Básico',
  BEEF11: 'Produtos de Consumo Básico',
  MNPR3: 'Produtos de Consumo Básico',
  MTRE3: 'Bens de Capital',
  MMXM3: 'Materiais',
  MMXM11: 'Materiais',
  MBLY3: 'Produtos de Consumo Discricionário',
  M1RN34: 'Saúde',
  MCOR34: 'Financeiro',
  MOSI3: 'Serviços de Comunicação',
  TMCO34: 'Produtos de Consumo Discricionário',
  M1SI34: 'Tecnologia da Informação',
  MOVI3: 'Industriais',
  MRVE3: 'Produtos de Consumo Discricionário',
  MULT3: 'Imóveis',
  MNDL3: 'Produtos de Consumo Discricionário',
  CASH3: 'Serviços de Comunicação',
  N1DA34: 'Financeiro',
  N1OV34: 'Energia',
  NTCO3: 'Produtos de Consumo Básico',
  P1IO34: 'Energia',
  NEOE3: 'Utilidades',
  NGRD3: 'Tecnologia da Informação',
  N1TA34: 'Tecnologia da Informação',
  NETE34: 'Serviços de Comunicação',
  N1EM34: 'Materiais',
  N1WS34: 'Serviços de Comunicação',
  N1IS34: 'Utilidades',
  J1WN34: 'Produtos de Consumo Discricionário',
  N1SC34: 'Industriais',
  N1TR34: '',
  S1YM34: '',
  N1UE34: 'Materiais',
  NUTR3: 'Materiais',
  N1XP34: 'Tecnologia da Informação',
  NVDC34: 'Tecnologia da Informação',
  N1VR34: 'Produtos de Consumo Discricionário',
  OXYP34: 'Energia',
  OPCT3: 'Industriais',
  ODPV3: 'Saúde',
  OIBR3: 'Serviços',
  OIBR4: 'Serviços',
  PRIO3: 'Energia',
  PDTC3: 'Tecnologia',
  PLAS3: 'Produtos de Consumo Discricionário',
  FRTA3: 'Produtos de Consumo Básico',
  TPIS3: 'Industriais',
  UGPA3: 'Energia',
  VLID3: 'Industriais',
  TUPY3: 'Produtos de Consumo Discricionário',
  UCAS3: 'Produtos de Consumo Discricionário',
  CTSA3: 'Produtos de Consumo Discricionário',
  VULC3: 'Consumo Cíclico',
  PETZ3: 'Produtos de Consumo Discricionário',
  ORVR3: 'Industriais',
  RAIL3: 'Industriais',
  QUAL3: 'Saúde',
  RAPT3: 'Industriais',
  RSID3: 'Produtos de Consumo Discricionário',
  TECN3: 'Produtos de Consumo Discricionário',
  SEQL3: 'Industriais',
  RCSL3: 'Industriais',
  SLED3: 'Produtos de Consumo Discricionário',
  SUZB3: 'Materiais',
  RDNI3: 'Bens de Capital',
  SGPS3: 'Produtos de Consumo Discricionário',
  TCSA3: 'Produtos de Consumo Discricionário',
  TGMA3: 'Industriais',
  TOTS3: 'Tecnologia da Informação',
  TRIS3: 'Produtos de Consumo Discricionário',
  VIVR3: 'Produtos de Consumo Discricionário',
  SQIA3: 'Tecnologia da Informação',
  AHEB3: 'Produtos de Consumo Discricionário',
  SAPR3: 'Utilidades',
  WEST3: 'Consumo Cíclico',
  SIMH3: 'Industriais',
  PDGR3: 'Produtos de Consumo Discricionário',
  PFRM3: 'Saúde',
  PSSA3: 'Financeiro',
  SBSP3: 'Utilidades',
  TIMS3: 'Serviços',
  TESA3: 'Produtos de Consumo Básico',
  TCNO3: 'Industriais',
  WIZS3: 'Financeiro',
  WHRL3: 'Produtos de Consumo Discricionário',
  TELB3: 'Serviços de Comunicação',
  VVAR3: 'Serviços',
  SMLS3: 'Serviços de Comunicação',
  VAMO3: 'Industriais',
  PETR3: 'Energia',
  PMAM3: 'Materiais Básicos',
  PTBL3: 'Industriais',
  UNIP3: 'Materiais',
  USIM3: 'Materiais',
  VALE3: 'Materiais',
  WEGE3: 'Industriais',
  RNEW3: 'Utilidades',
  TEND3: 'Serviços',
  PLPL3: 'Produtos de Consumo Discricionário',
  O1KE34: 'Energia',
  P1AC34: 'Industriais',
  P1KG34: 'Materiais',
  PATI3: 'Materiais',
  PATI4: 'Materiais',
  P1HC34: 'Industriais',
  RAPT4: 'Industriais',
  YDUQ3: 'Produtos de Consumo Discricionário',
  P1AY34: 'Tecnologia da Informação',
  P1YC34: '',
  P1NR34: 'Industriais',
  P1KI34: 'Saúde',
  PETR4: 'Energia',
  RECV3: '',
  PTNT4: 'Produtos de Consumo Discricionário',
  PTNT3: 'Produtos de Consumo Discricionário',
  PINE4: 'Financeiro',
  SAPR4: 'Utilidades',
  RCSL4: 'Industriais',
  SMLS3T: '',
  TAEE4: 'Utilidades',
  TEKA4: 'Produtos de Consumo Discricionário',
  TELB4: 'Serviços de Comunicação',
  MWET4: 'Produtos de Consumo Discricionário',
  TCNO4: 'Industriais',
  TXRX4: 'Produtos de Consumo Discricionário',
  CTSA4: 'Produtos de Consumo Discricionário',
  WHRL4: 'Produtos de Consumo Discricionário',
  SHUL4: 'Industriais',
  RNEW4: 'Utilidades',
  TEKA3: 'Produtos de Consumo Discricionário',
  UNIP5: 'Materiais',
  AHEB5: 'Produtos de Consumo Discricionário',
  USIM5: 'Materiais',
  SOND5: 'Industriais',
  SOND6: 'Industriais',
  UNIP6: 'Materiais',
  USIM6: 'Materiais',
  SNSY5: 'Materiais',
  PSVM11: 'Industriais',
  P1PL34: 'Utilidades',
  PPLA11: 'Financeiro',
  TKNO4: 'Materiais',
  P1GR34: 'Financeiro',
  P1LD34: 'Imóveis',
  TEPP11: 'Financeiro',
  P1DT34: 'Financeiro',
  P1SA34: 'Imóveis',
  P1HM34: 'Produtos de Consumo Discricionário',
  P1VH34: 'Produtos de Consumo Discricionário',
  Q1RV34: 'Tecnologia da Informação',
  Q1UA34: 'Industriais',
  V1NO34: 'Imóveis',
  REGN34: 'Saúde',
  TXRX3: 'Produtos de Consumo Discricionário',
  RNEW11: 'Utilidades',
  U1RI34: 'Industriais',
  R1SG34: 'Industriais',
  W1YN34: 'Produtos de Consumo Discricionário',
  RIOT34: 'Materiais',
  R1KU34: '',
  R1OL34: 'Industriais',
  R1OP34: 'Industriais',
  SAPR11: 'Utilidades',
  SNSY3: 'Materiais',
  SLED4: 'Produtos de Consumo Discricionário',
  S1TX34: '',
  XPSF11: 'Financeiro',
  S1SL34: 'Tecnologia da Informação',
  S1NA34: 'Industriais',
  S2NW34: '',
  S1PO34: 'Serviços de Comunicação',
  S1TT34: 'Financeiro',
  S1YK34: 'Saúde',
  S1NP34: 'Tecnologia da Informação',
  S1YY34: 'Produtos de Consumo Básico',
  TAEE11: 'Utilidades',
  TAEE3: 'Utilidades',
  I1RP34: 'Industriais',
  T1EC34: 'Energia',
  U1BE34: 'Industriais',
  T1FX34: 'Saúde',
  TLNC34: 'Serviços de Comunicação',
  T1XT34: 'Industriais',
  T1MU34: 'Serviços de Comunicação',
  W1LT34: 'Financeiro',
  T1DG34: 'Industriais',
  T1RI34: 'Serviços de Comunicação',
  T1WL34: 'Tecnologia da Informação',
  U1DR34: 'Imóveis',
  V1TA34: 'Imóveis',
  C1BS34: 'Serviços de Comunicação',
  VIVA3: 'Produtos de Consumo Discricionário',
  W1EL34: 'Imóveis',
  MWET3: 'Produtos de Consumo Discricionário',
  W1HR34: 'Produtos de Consumo Discricionário',
  W1IX34: 'Tecnologia da Informação',
  W1DA34: 'Tecnologia da Informação',
  W1PP34: '',
  X1LN34: 'Tecnologia da Informação',
  X1YL34: 'Industriais',
  Z1TS34: 'Saúde'
}

export default {
  ticker2sector
}
